-- AUTO-GENERATED by scripts/generate_mental_models.py
-- Mental Models for Code track + concept atoms + diagnostic bank.
-- Track + modules + the foundation concepts seed here.

insert into public.tracks (id, slug, title, description, difficulty, is_published) values (
  '00000000-0000-0000-0000-000000000004',
  'mental-models',
  E'Mental Models for Code',
  E'Learn how to think about code, not just write it. Concept-by-concept: variables, references, control flow, recursion, complexity, state machines, and the memory model. Each concept follows a six-stage UNIT — Try, Read, Play, Check, Apply, Reflect — grounded in cognitive-load and productive-failure research.',
  'foundation',
  true
)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  difficulty = excluded.difficulty,
  is_published = excluded.is_published;

delete from public.concept_prereqs where concept_id in (select id from public.concepts);
delete from public.concepts where slug like '%-%';
delete from public.diagnostic_questions where track_slug = 'mental-models';

insert into public.concepts (
  id, slug, layer, topic_slug, title, one_line, try_prompt_md, try_kind, try_expected_attempts_json, exposition_md, worked_example_md, play_widget_kind, play_widget_json, check_mcqs_json, apply_challenge_slug, reflect_question, reflect_rubric_json, recall_checks_json, order_index
) values (
  '00000000-0000-0000-0000-000000000400',
  'variables-names',
  'universal',
  null,
  E'Variables and names',
  E'A variable is a name bound to a value in a scope.',
  E'**Try.** Predict the output of this snippet — *no running it, no looking it up*. If you''re not sure, write your best guess and a one-line reason.\n\n```python\na = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)\n```',
  'text-reasoning',
  E'[{"pattern":"\\\\[1,\\\\s*2,\\\\s*3\\\\]","callback_md":"You predicted `[1, 2, 3]` — that''s what would happen if `b = a` made a *copy*. It doesn''t; it makes a second name for the same list. The Read stage shows why."},{"pattern":"\\\\[1,\\\\s*2,\\\\s*3,\\\\s*4\\\\]","callback_md":"You predicted `[1, 2, 3, 4]` — correct. The Read stage shows *why* this is the case: `b = a` doesn''t copy the list, it just binds a second name to it."}]'::jsonb,
  E'A variable is not a box. It''s a **name bound to a value in a scope**. Two names can be bound to the same value at once; mutating that value affects every name pointing at it.\n\nThe mental model that catches *most* Python aliasing bugs is this: imagine an arrow from each name to the underlying object. `a = [1, 2, 3]` draws one arrow. `b = a` draws a second arrow to the *same* list (no second list is created). When you call `b.append(4)`, the list both arrows point at gets a new element — so `a` and `b` both reflect the change.\n\nThis is different from immutable values like ints and strings. `x = 5; y = x; y = 6` doesn''t change `x`, because integers are immutable — `y = 6` rebinds `y` to a different object instead of mutating the old one.',
  E'```python\n# Two names, one list.\na = [1, 2, 3]    # ''a'' → [1, 2, 3]\nb = a            # ''b'' → same [1, 2, 3]; no copy made\nb.append(4)      # the shared list gets a new element\nprint(a)         # [1, 2, 3, 4]\nprint(b)         # [1, 2, 3, 4]\nprint(a is b)    # True — same underlying object\n```',
  'code-stepper',
  E'{"title":"Step through a name-binding scenario","code":"a = [1, 2, 3]\\nb = a\\nb.append(4)\\nprint(a)","steps":[{"line":1,"bindings":{"a":"→ list#1 [1, 2, 3]"},"heap":[{"id":"list#1","value":"[1, 2, 3]"}],"caption":"`a` is bound to a list — one arrow from `a` to list#1."},{"line":2,"bindings":{"a":"→ list#1","b":"→ list#1"},"heap":[{"id":"list#1","value":"[1, 2, 3]"}],"caption":"`b = a` does NOT copy — it draws a second arrow to the same list#1."},{"line":3,"bindings":{"a":"→ list#1","b":"→ list#1"},"heap":[{"id":"list#1","value":"[1, 2, 3, 4]"}],"caption":"`b.append(4)` mutates list#1 itself — both `a` and `b` see the change."},{"line":4,"bindings":{"a":"→ list#1","b":"→ list#1"},"heap":[{"id":"list#1","value":"[1, 2, 3, 4]"}],"caption":"`print(a)` reads the (now-mutated) list. Output: [1, 2, 3, 4]."}]}'::jsonb,
  E'[{"q":"Given `xs = {''k'': 1}` and `ys = xs`, what does `ys[''k''] = 9; print(xs)` print?","options":["{''k'': 1}","{''k'': 9}","TypeError","None"],"correct":1,"why":"`ys = xs` binds `ys` to the *same* dict. Mutating via either name is visible through the other."},{"q":"Given `s = ''hi''; t = s; t = t + ''!''`, what does `print(s)` print?","options":["''hi''","''hi!''","''!hi''","Error"],"correct":0,"why":"Strings are immutable. `t = t + ''!''` rebinds `t` to a new string; `s` still points at the original ''hi''."}]'::jsonb,
  null,
  E'In two sentences, explain to a colleague what a *variable* is in Python — and why `b = a` followed by `b.append(4)` changes `a` too.',
  E'{"must_mention":["name","value","scope"],"must_distinguish":[["binding","copying"],["mutable","immutable"]],"must_explain":["two names can be bound to the same object","mutating the object affects every name bound to it"]}'::jsonb,
  E'[{"kind":"mcq","q":"Given `xs = [1]; ys = xs; ys.append(2)`, what is `xs`?","options":["[1]","[1, 2]","TypeError"],"correct":1},{"kind":"mcq","q":"If `s = ''a''; t = s; t = ''b''`, what is `s`?","options":["''a''","''b''","None"],"correct":0},{"kind":"mcq","q":"What does `b = a` do when `a` is a list?","options":["Copies the list","Creates a second name for the same list","Raises an exception"],"correct":1}]'::jsonb,
  100
);

insert into public.concepts (
  id, slug, layer, topic_slug, title, one_line, try_prompt_md, try_kind, try_expected_attempts_json, exposition_md, worked_example_md, play_widget_kind, play_widget_json, check_mcqs_json, apply_challenge_slug, reflect_question, reflect_rubric_json, recall_checks_json, order_index
) values (
  '00000000-0000-0000-0000-000000000401',
  'references-values',
  'universal',
  null,
  E'References and values',
  E'Mutating an object is visible through every name bound to it.',
  E'**Try.** Predict the output of this snippet — without running it. It''s a famous Python gotcha.\n\n```python\ndef add_one(xs=[]):\n    xs.append(1)\n    return xs\n\nprint(add_one())\nprint(add_one())\n```',
  'text-reasoning',
  E'[{"pattern":"\\\\[1\\\\]\\\\s*\\\\[1\\\\]","callback_md":"You predicted two `[1]`s — that''s what you''d get if Python re-created the default list each call. It doesn''t."},{"pattern":"\\\\[1\\\\]\\\\s*\\\\[1,\\\\s*1\\\\]","callback_md":"Correct. The default value is evaluated *once* at function-definition time; every call without an explicit `xs` shares that same list."}]'::jsonb,
  E'Python evaluates default arguments **once**, at function definition time. The resulting object is then shared across every call that doesn''t pass that argument explicitly. If the default is a mutable object — a list, dict, set — every call''s mutations accumulate on the same instance.\n\nThe fix is the **None-sentinel** pattern: default to `None`, then check inside the function and create a fresh object per call. This is so common it''s a 30-second answer in every senior Python interview.\n\nMore broadly: when a function receives a mutable argument, decide explicitly whether you want to mutate it (visible to the caller, like `list.sort()`) or return a new object (no caller side effects, like `sorted()`). Either is fine; mixing them is what causes bugs.',
  E'```python\n# The bug:\ndef add_one(xs=[]):\n    xs.append(1)        # mutates the shared default\n    return xs\n\nprint(add_one())        # [1]\nprint(add_one())        # [1, 1] — same list!\n\n# The fix:\ndef add_one_safe(xs=None):\n    if xs is None:\n        xs = []         # fresh list per call\n    xs.append(1)\n    return xs\n\nprint(add_one_safe())   # [1]\nprint(add_one_safe())   # [1] — independent\n```',
  'memory-model-viewer',
  E'{"title":"The shared default list","frames":[{"caption":"At function definition: Python builds the default list once.","stack":[{"name":"(module)","vars":{}}],"heap":[{"id":"list#1","value":"[]","labels":["add_one.__defaults__[0]"]}]},{"caption":"Call 1: xs binds to list#1 → append(1) mutates it.","stack":[{"name":"(module)","vars":{}},{"name":"add_one","vars":{"xs":"→ list#1"}}],"heap":[{"id":"list#1","value":"[1]","labels":["add_one.__defaults__[0]","xs"]}]},{"caption":"Call 2: xs binds to the SAME list#1 → another mutation.","stack":[{"name":"(module)","vars":{}},{"name":"add_one","vars":{"xs":"→ list#1"}}],"heap":[{"id":"list#1","value":"[1, 1]","labels":["add_one.__defaults__[0]","xs"]}]}]}'::jsonb,
  E'[{"q":"What does this print?\\n\\n```\\ndef f(d={}):\\n    d[''n''] = d.get(''n'', 0) + 1\\n    return d\\n\\nprint(f()); print(f())\\n```","options":["{''n'': 1} {''n'': 1}","{''n'': 1} {''n'': 2}","{''n'': 0} {''n'': 1}","TypeError"],"correct":1,"why":"Same trap as lists. The dict default is built once and reused across calls."},{"q":"Which is the safe default for a list-typed argument in Python?","options":["`def f(xs=[]):`","`def f(xs=list()):`","`def f(xs=None):` and create the list inside","`def f(xs):` and document that the caller must pass one"],"correct":2,"why":"The None-sentinel pattern is the canonical fix — a fresh list per call, no shared state."}]'::jsonb,
  null,
  E'In two sentences, explain why mutating a default argument value in Python can leak state across calls — and how to fix it.',
  E'{"must_mention":["default","mutable","shared"],"must_distinguish":[["evaluation at definition","evaluation per call"]],"must_explain":["the default object is created once","every call without the argument reuses that same object","use None as the sentinel and create a fresh object inside"]}'::jsonb,
  E'[{"kind":"mcq","q":"Calling `f()` twice when `f` has `xs=[]` as default and appends 1 produces what after the second call?","options":["[1]","[1, 1]","[]"],"correct":1},{"kind":"mcq","q":"The Pythonic safe-default pattern is:","options":["`xs=[]`","`xs=None` + check inside","`xs=list()`"],"correct":1},{"kind":"mcq","q":"Default arguments in Python are evaluated…","options":["once, at definition","every call","lazily, on first use"],"correct":0}]'::jsonb,
  200
);

insert into public.concepts (
  id, slug, layer, topic_slug, title, one_line, try_prompt_md, try_kind, try_expected_attempts_json, exposition_md, worked_example_md, play_widget_kind, play_widget_json, check_mcqs_json, apply_challenge_slug, reflect_question, reflect_rubric_json, recall_checks_json, order_index
) values (
  '00000000-0000-0000-0000-000000000402',
  'control-flow',
  'universal',
  null,
  E'Control flow',
  E'Code runs top-to-bottom unless an if, loop, or function call diverts it.',
  E'**Try.** Predict what this prints — and how many times the body of the loop runs.\n\n```python\nn = 0\nfor i in range(3):\n    if i == 1:\n        continue\n    n += i\nprint(n)\n```',
  'text-reasoning',
  E'[{"pattern":"\\\\b3\\\\b","callback_md":"You predicted 3 — that''s the answer if all three iterations contributed. `continue` skipped one."},{"pattern":"\\\\b2\\\\b","callback_md":"Correct. i=0 adds 0, i=1 hits `continue` so skips the addition, i=2 adds 2 — total 2."}]'::jsonb,
  E'Code is **causal** — earlier statements set up the state that later statements depend on. Reading code is therefore a form of mental simulation: hold the current values of the live variables in your head, then step forward.\n\nControl-flow primitives are the three ways execution diverges from straight-line:\n\n1. **Branching** (`if` / `elif` / `else`): exactly one block runs based on a condition. Track which.\n2. **Looping** (`for` / `while`): a block runs multiple times. Track the loop variable and the accumulator.\n3. **Function calls**: execution jumps to the function body, runs to a `return` (or implicit None), and resumes one line after the call. Track which frame you''re in.\n\n`break` exits the nearest loop. `continue` skips to the next iteration. Both are early-exit shortcuts — easy to misread.',
  E'```python\n# Sum the even numbers under 6.\ntotal = 0\nfor i in range(6):\n    if i % 2 != 0:\n        continue        # skip odd i''s\n    total += i          # only runs for i in {0, 2, 4}\nprint(total)            # 6\n```',
  'code-stepper',
  E'{"title":"Step through a continue-in-a-loop","code":"total = 0\\nfor i in range(6):\\n    if i % 2 != 0:\\n        continue\\n    total += i\\nprint(total)","steps":[{"line":1,"bindings":{"total":"0"},"caption":"`total` starts at 0."},{"line":2,"bindings":{"total":"0","i":"0"},"caption":"First iteration: i=0 (even)."},{"line":5,"bindings":{"total":"0","i":"0"},"caption":"0 % 2 == 0, so we skip continue and reach the add."},{"line":5,"bindings":{"total":"0","i":"1"},"caption":"Second iteration: i=1 (odd). Condition triggers."},{"line":4,"bindings":{"total":"0","i":"1"},"caption":"`continue` — jump straight back to the loop header. `total` unchanged."},{"line":5,"bindings":{"total":"2","i":"2"},"caption":"i=2 (even). 0 + 2 = 2."},{"line":5,"bindings":{"total":"2","i":"3"},"caption":"i=3 (odd). continue again. No change."},{"line":5,"bindings":{"total":"6","i":"4"},"caption":"i=4 (even). 2 + 4 = 6."},{"line":5,"bindings":{"total":"6","i":"5"},"caption":"i=5 (odd). continue. Final total 6."},{"line":6,"bindings":{"total":"6"},"caption":"Print 6 — the sum of even numbers 0..4."}]}'::jsonb,
  E'[{"q":"How many times does the body of `for i in range(4): if i == 2: break; print(i)` actually print?","options":["1","2","3","4"],"correct":1,"why":"`break` exits the loop entirely at i=2 — only i=0 and i=1 reach the print, so 2 lines."},{"q":"What does `continue` do inside a `for` loop?","options":["Exits the loop entirely","Skips the rest of the current iteration and starts the next","Restarts the loop from the beginning","Pauses execution"],"correct":1,"why":"`continue` is a per-iteration shortcut, not a per-loop shortcut. The loop header runs again immediately."}]'::jsonb,
  null,
  E'In two sentences, describe how `break` and `continue` differ — and why someone reading code at a glance might confuse them.',
  E'{"must_mention":["break","continue","loop"],"must_distinguish":[["exit the loop","skip the iteration"]],"must_explain":["break exits the enclosing loop entirely","continue jumps to the next iteration of the same loop","both are early-exit shortcuts inside the loop body"]}'::jsonb,
  E'[{"kind":"mcq","q":"`break` inside a `for` loop:","options":["skips one iteration","exits the loop","restarts the loop"],"correct":1},{"kind":"mcq","q":"`continue` inside a `for` loop:","options":["skips to next iteration","exits the loop","raises an exception"],"correct":0},{"kind":"mcq","q":"If an `if` condition is False, the matching block:","options":["runs","is skipped","raises TypeError"],"correct":1}]'::jsonb,
  300
);

insert into public.concepts (
  id, slug, layer, topic_slug, title, one_line, try_prompt_md, try_kind, try_expected_attempts_json, exposition_md, worked_example_md, play_widget_kind, play_widget_json, check_mcqs_json, apply_challenge_slug, reflect_question, reflect_rubric_json, recall_checks_json, order_index
) values (
  '00000000-0000-0000-0000-000000000404',
  'recursion',
  'universal',
  null,
  E'Recursion',
  E'A function that calls itself — with a base case and a smaller subproblem.',
  E'**Try.** This is a classic recursive factorial:\n\n```python\ndef fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)\n\nprint(fact(4))\n```\n\nPredict what `fact(4)` returns — and how many times `fact` is called in total.',
  'text-reasoning',
  E'[{"pattern":"\\\\b24\\\\b.*[3-5]","callback_md":"You got the value (24) and an attempt at the call count. The exact number of calls is 4 — fact(4), fact(3), fact(2), fact(1). The Read covers why."},{"pattern":"\\\\b24\\\\b","callback_md":"Value correct (24 = 4 × 3 × 2 × 1). The call count matters for the next stage — keep that in mind."}]'::jsonb,
  E'A recursive function calls itself. To not loop forever, every recursion needs:\n\n1. A **base case** — an input the function can answer without calling itself (here: `n <= 1` returns 1).\n2. A **recursive case** — a step that reduces the input toward the base case (here: `n - 1`) and combines the subresult (here: multiplies by `n`).\n\nEach call pushes a new **stack frame** holding the call''s local variables. The frame stays on the stack until its function returns. For `fact(4)`, the stack grows: fact(4) → fact(3) → fact(2) → fact(1). fact(1) returns 1, then each outer frame collapses, multiplying as it goes: 1, 2, 6, 24.\n\nForget the base case and the stack grows forever — you get `RecursionError: maximum recursion depth exceeded`. Forget to reduce toward the base case and the same.',
  E'```python\ndef fact(n):\n    if n <= 1:                # base case\n        return 1\n    return n * fact(n - 1)    # recursive case\n\nprint(fact(4))                # 24\n```\n\nCall trace:\n  fact(4) → 4 * fact(3) → 4 * (3 * fact(2)) → 4 * (3 * (2 * fact(1)))\n  fact(1) returns 1, then we unwind: 2*1=2, 3*2=6, 4*6=24.',
  'call-stack-visualiser',
  E'{"title":"Watch the call stack of fact(4)","function_name":"fact","frames":[{"caption":"Initial call.","stack":["fact(4)"]},{"caption":"fact(4) calls fact(3).","stack":["fact(4)","fact(3)"]},{"caption":"fact(3) calls fact(2).","stack":["fact(4)","fact(3)","fact(2)"]},{"caption":"fact(2) calls fact(1).","stack":["fact(4)","fact(3)","fact(2)","fact(1)"]},{"caption":"fact(1) hits the base case and returns 1. The frame pops.","stack":["fact(4)","fact(3)","fact(2) ← 1"]},{"caption":"fact(2) computes 2 * 1 = 2 and returns. Pop.","stack":["fact(4)","fact(3) ← 2"]},{"caption":"fact(3) computes 3 * 2 = 6 and returns. Pop.","stack":["fact(4) ← 6"]},{"caption":"fact(4) computes 4 * 6 = 24 and returns. Stack empty.","stack":[]}]}'::jsonb,
  E'[{"q":"What''s missing from this recursive function?\\n\\n```\\ndef count_down(n):\\n    print(n)\\n    count_down(n - 1)\\n```","options":["Nothing — it works","A base case","A return statement","A loop"],"correct":1,"why":"No base case → infinite recursion → RecursionError. Add `if n <= 0: return` at the top."},{"q":"How many stack frames are live (not yet returned) at the moment `fact(1)` is about to compute its return value, when called as `fact(5)`?","options":["1","3","5","Infinite"],"correct":2,"why":"fact(5), fact(4), fact(3), fact(2), fact(1) — five frames all live until the base case starts unwinding."}]'::jsonb,
  null,
  E'In two sentences, explain why a recursive function needs a base case — and what happens at runtime if you forget it.',
  E'{"must_mention":["base case","stack","recursive"],"must_distinguish":[["recursive case","base case"]],"must_explain":["the base case is the input the function can answer without recursing","without it the stack grows until RecursionError","each call adds a frame; the base case starts the unwinding"]}'::jsonb,
  E'[{"kind":"mcq","q":"A recursive function with no base case will:","options":["return None","raise RecursionError","loop forever"],"correct":1},{"kind":"mcq","q":"Each recursive call adds:","options":["a CPU register","a stack frame","a global variable"],"correct":1},{"kind":"mcq","q":"fact(3) calls how many functions before the first return?","options":["1","3","9"],"correct":1}]'::jsonb,
  500
);

insert into public.concept_prereqs (concept_id, prereq_concept_id) select c.id, p.id from public.concepts c, public.concepts p where c.slug = 'references-values' and p.slug = 'variables-names' on conflict do nothing;
insert into public.concept_prereqs (concept_id, prereq_concept_id) select c.id, p.id from public.concepts c, public.concepts p where c.slug = 'control-flow' and p.slug = 'variables-names' on conflict do nothing;
insert into public.concept_prereqs (concept_id, prereq_concept_id) select c.id, p.id from public.concepts c, public.concepts p where c.slug = 'recursion' and p.slug = 'functions' on conflict do nothing;

insert into public.diagnostic_questions (
  id, track_slug, layer, question_md, question_kind, options_json, expected_answer, maps_to_concept_slugs, order_index
) values (
  '00000000-0000-0000-0000-0000000004f0',
  'mental-models',
  'universal',
  E'Given `a = [1, 2]; b = a; b.append(3)`, what does `print(a)` print?',
  'mcq',
  E'{"options":["[1, 2]","[1, 2, 3]","[3]","TypeError"],"correct":1}'::jsonb,
  E'1',
  array['variables-names', 'references-values']::text[],
  1
);
