-- AUTO-GENERATED by scripts/generate_mental_models.py
-- Mental Models for Code track + concept atoms + diagnostic bank.
-- Track + modules + the foundation concepts seed here.

insert into public.tracks (id, slug, title, description, difficulty, is_published) values (
  '00000000-0000-0000-0000-000000000004',
  'mental-models',
  E'Mental Models for Code',
  E'Learn how to think about code, not just write it. Concept-by-concept: variables, references, control flow, recursion, complexity, state machines, and the memory model. Each concept follows a six-stage UNIT — Try, Read, Play, Check, Apply, Reflect — grounded in cognitive-load and productive-failure research.',
  'foundation',
  true
)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  difficulty = excluded.difficulty,
  is_published = excluded.is_published;

delete from public.concept_prereqs where concept_id in (select id from public.concepts);
delete from public.concepts where slug like '%-%';
delete from public.diagnostic_questions where track_slug = 'mental-models';

insert into public.concepts (
  id, slug, layer, topic_slug, title, one_line, try_prompt_md, try_kind, try_expected_attempts_json, exposition_md, worked_example_md, play_widget_kind, play_widget_json, check_mcqs_json, apply_challenge_slug, reflect_question, reflect_rubric_json, recall_checks_json, order_index
) values (
  '00000000-0000-0000-0000-000000000400',
  'variables-names',
  'universal',
  null,
  E'Variables and names',
  E'A variable is a name bound to a value in a scope.',
  E'**Try.** Predict the output of this snippet — *no running it, no looking it up*. If you''re not sure, write your best guess and a one-line reason.\n\n```python\na = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)\n```',
  'text-reasoning',
  E'[{"pattern":"\\\\[1,\\\\s*2,\\\\s*3\\\\]","callback_md":"You predicted `[1, 2, 3]` — that''s what would happen if `b = a` made a *copy*. It doesn''t; it makes a second name for the same list. The Read stage shows why."},{"pattern":"\\\\[1,\\\\s*2,\\\\s*3,\\\\s*4\\\\]","callback_md":"You predicted `[1, 2, 3, 4]` — correct. The Read stage shows *why* this is the case: `b = a` doesn''t copy the list, it just binds a second name to it."}]'::jsonb,
  E'A variable is not a box. It''s a **name bound to a value in a scope**. Two names can be bound to the same value at once; mutating that value affects every name pointing at it.\n\nThe mental model that catches *most* Python aliasing bugs is this: imagine an arrow from each name to the underlying object. `a = [1, 2, 3]` draws one arrow. `b = a` draws a second arrow to the *same* list (no second list is created). When you call `b.append(4)`, the list both arrows point at gets a new element — so `a` and `b` both reflect the change.\n\nThis is different from immutable values like ints and strings. `x = 5; y = x; y = 6` doesn''t change `x`, because integers are immutable — `y = 6` rebinds `y` to a different object instead of mutating the old one.',
  E'```python\n# Two names, one list.\na = [1, 2, 3]    # ''a'' → [1, 2, 3]\nb = a            # ''b'' → same [1, 2, 3]; no copy made\nb.append(4)      # the shared list gets a new element\nprint(a)         # [1, 2, 3, 4]\nprint(b)         # [1, 2, 3, 4]\nprint(a is b)    # True — same underlying object\n```',
  'code-stepper',
  E'{"title":"Step through a name-binding scenario","code":"a = [1, 2, 3]\\nb = a\\nb.append(4)\\nprint(a)","steps":[{"line":1,"bindings":{"a":"→ list#1 [1, 2, 3]"},"heap":[{"id":"list#1","value":"[1, 2, 3]"}],"caption":"`a` is bound to a list — one arrow from `a` to list#1."},{"line":2,"bindings":{"a":"→ list#1","b":"→ list#1"},"heap":[{"id":"list#1","value":"[1, 2, 3]"}],"caption":"`b = a` does NOT copy — it draws a second arrow to the same list#1."},{"line":3,"bindings":{"a":"→ list#1","b":"→ list#1"},"heap":[{"id":"list#1","value":"[1, 2, 3, 4]"}],"caption":"`b.append(4)` mutates list#1 itself — both `a` and `b` see the change."},{"line":4,"bindings":{"a":"→ list#1","b":"→ list#1"},"heap":[{"id":"list#1","value":"[1, 2, 3, 4]"}],"caption":"`print(a)` reads the (now-mutated) list. Output: [1, 2, 3, 4]."}]}'::jsonb,
  E'[{"q":"Given `xs = {''k'': 1}` and `ys = xs`, what does `ys[''k''] = 9; print(xs)` print?","options":["{''k'': 1}","{''k'': 9}","TypeError","None"],"correct":1,"why":"`ys = xs` binds `ys` to the *same* dict. Mutating via either name is visible through the other."},{"q":"Given `s = ''hi''; t = s; t = t + ''!''`, what does `print(s)` print?","options":["''hi''","''hi!''","''!hi''","Error"],"correct":0,"why":"Strings are immutable. `t = t + ''!''` rebinds `t` to a new string; `s` still points at the original ''hi''."}]'::jsonb,
  null,
  E'In two sentences, explain to a colleague what a *variable* is in Python — and why `b = a` followed by `b.append(4)` changes `a` too.',
  E'{"must_mention":["name","value","scope"],"must_distinguish":[["binding","copying"],["mutable","immutable"]],"must_explain":["two names can be bound to the same object","mutating the object affects every name bound to it"]}'::jsonb,
  E'[{"kind":"mcq","q":"Given `xs = [1]; ys = xs; ys.append(2)`, what is `xs`?","options":["[1]","[1, 2]","TypeError"],"correct":1},{"kind":"mcq","q":"If `s = ''a''; t = s; t = ''b''`, what is `s`?","options":["''a''","''b''","None"],"correct":0},{"kind":"mcq","q":"What does `b = a` do when `a` is a list?","options":["Copies the list","Creates a second name for the same list","Raises an exception"],"correct":1}]'::jsonb,
  100
);

insert into public.diagnostic_questions (
  id, track_slug, layer, question_md, question_kind, options_json, expected_answer, maps_to_concept_slugs, order_index
) values (
  '00000000-0000-0000-0000-0000000004f0',
  'mental-models',
  'universal',
  E'Given `a = [1, 2]; b = a; b.append(3)`, what does `print(a)` print?',
  'mcq',
  E'{"options":["[1, 2]","[1, 2, 3]","[3]","TypeError"],"correct":1}'::jsonb,
  E'1',
  array['variables-names', 'references-values']::text[],
  1
);
