-- AUTO-GENERATED by scripts/generate_python_basics.py
-- Python Basics track: 1 track, 7 modules, 25 challenges.

insert into public.tracks (id, slug, title, description, difficulty, is_published)
values (
  '00000000-0000-0000-0000-000000000002',
  'python-basics',
  E'Python Basics',
  E'Your first 25 lessons in Python — variables, conditionals, loops, functions, classes. Step-by-step exercises that run entirely in your browser. No prior coding experience required.',
  'beginner',
  true
)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  difficulty = excluded.difficulty,
  is_published = excluded.is_published;

insert into public.modules (id, track_id, slug, title, order_index)
values (
  '00000000-0000-0000-0000-000000000020',
  '00000000-0000-0000-0000-000000000002',
  'python-basics-first-steps',
  E'Module 1 — First steps',
  1
)
on conflict (track_id, slug) do update set
  title = excluded.title,
  order_index = excluded.order_index;

insert into public.modules (id, track_id, slug, title, order_index)
values (
  '00000000-0000-0000-0000-000000000021',
  '00000000-0000-0000-0000-000000000002',
  'python-basics-making-decisions',
  E'Module 2 — Making decisions',
  2
)
on conflict (track_id, slug) do update set
  title = excluded.title,
  order_index = excluded.order_index;

insert into public.modules (id, track_id, slug, title, order_index)
values (
  '00000000-0000-0000-0000-000000000022',
  '00000000-0000-0000-0000-000000000002',
  'python-basics-doing-things-many-times',
  E'Module 3 — Doing things many times',
  3
)
on conflict (track_id, slug) do update set
  title = excluded.title,
  order_index = excluded.order_index;

insert into public.modules (id, track_id, slug, title, order_index)
values (
  '00000000-0000-0000-0000-000000000023',
  '00000000-0000-0000-0000-000000000002',
  'python-basics-collections',
  E'Module 4 — Collections',
  4
)
on conflict (track_id, slug) do update set
  title = excluded.title,
  order_index = excluded.order_index;

insert into public.modules (id, track_id, slug, title, order_index)
values (
  '00000000-0000-0000-0000-000000000024',
  '00000000-0000-0000-0000-000000000002',
  'python-basics-functions',
  E'Module 5 — Functions',
  5
)
on conflict (track_id, slug) do update set
  title = excluded.title,
  order_index = excluded.order_index;

insert into public.modules (id, track_id, slug, title, order_index)
values (
  '00000000-0000-0000-0000-000000000025',
  '00000000-0000-0000-0000-000000000002',
  'python-basics-real-code',
  E'Module 6 — Real code',
  6
)
on conflict (track_id, slug) do update set
  title = excluded.title,
  order_index = excluded.order_index;

insert into public.modules (id, track_id, slug, title, order_index)
values (
  '00000000-0000-0000-0000-000000000026',
  '00000000-0000-0000-0000-000000000002',
  'python-basics-putting-it-together',
  E'Module 7 — Putting it together',
  7
)
on conflict (track_id, slug) do update set
  title = excluded.title,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000200',
  '00000000-0000-0000-0000-000000000020',
  'python-basics-01-hello-python',
  E'Hello Python',
  E'The simplest way to make Python do something visible is to call `print()`.',
  E'Use `print()` to display text.',
  E'**Concept.** `print()` is a built-in function. Whatever you pass to it appears as output. Text in quotes is a **string**; single (`''`) or double (`"`) both work.\n\n**Example.**\n\n```python\nprint("Hello, world!")\n```\n\n**Your turn.** Replace `___` so the program prints `hello, Python!`.\n\n**Expected.** `hello, Python!`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'io'],
  true,
  1
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000201',
  '00000000-0000-0000-0000-000000000020',
  'python-basics-02-variables',
  E'Variables',
  E'Programs are useful when they remember things. A variable is how Python remembers a value.',
  E'Assign a value to a variable and print it back.',
  E'**Concept.** `name = value` stores `value` under the name `name`. Reading the name later gives you back the value. Names use letters/digits/underscores and avoid Python keywords like `print`.\n\n**Example.**\n\n```python\nname = "Ada"\nprint(name)  # Ada\n```\n\n**Your turn.** Create a variable called `language` holding `"Python"`, then print it.\n\n**Expected.** `Python`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'variables'],
  true,
  2
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000202',
  '00000000-0000-0000-0000-000000000020',
  'python-basics-03-strings-and-f-strings',
  E'Strings and f-strings',
  E'f-strings drop variables into text cleanly, without gluing strings with `+`.',
  E'Use an f-string to embed a variable in text.',
  E'**Concept.** An f-string is a string prefixed with `f`. Anything inside `{}` is evaluated as Python and inserted: `f"Hello, {name}!"` becomes `"Hello, Ada!"` when `name = "Ada"`.\n\n**Example.**\n\n```python\nname = "Ada"\nprint(f"Hello, {name}!")  # Hello, Ada!\n```\n\n**Your turn.** Fill in `___` so the output is `My favourite language is Python`.\n\n**Expected.** `My favourite language is Python`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'strings'],
  true,
  3
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000203',
  '00000000-0000-0000-0000-000000000020',
  'python-basics-04-numbers-and-arithmetic',
  E'Numbers and arithmetic',
  E'Python supports the standard arithmetic operators plus a couple of extras.',
  E'Predict the output of an arithmetic expression.',
  E'**Concept.** `+ - * /` work as expected. `/` always returns a float. `//` is integer division (drops the remainder). `%` is the remainder. `**` is power. `*` happens before `+`, like normal maths.\n\n**Example.**\n\n```python\nprint(7 / 2)   # 3.5\nprint(7 // 2)  # 3\nprint(7 % 2)   # 1\nprint(2 ** 3)  # 8\n```\n\n**Predict.** What does this print?\n\n**Expected.** `16`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'arithmetic'],
  true,
  4
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000204',
  '00000000-0000-0000-0000-000000000020',
  'python-basics-05-type-conversion',
  E'Type conversion',
  E'Numbers from users often arrive as strings — and strings won''t add to numbers without converting.',
  E'Convert a string to an int so you can do maths with it.',
  E'**Concept.** `int(x)`, `float(x)`, and `str(x)` return a NEW value of that type; they don''t change `x`. `int("2") + 3` is `5`, but `"2" + "3"` is `"23"`.\n\n**Example.**\n\n```python\nprint(2 + 3)         # 5  (number addition)\nprint("2" + "3")     # 23 (string concatenation!)\nprint(int("2") + 3)  # 5\n```\n\n**Your turn.** Convert the string `"42"` to an integer and add 8.\n\n**Expected.** `50`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'types'],
  true,
  5
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000205',
  '00000000-0000-0000-0000-000000000021',
  'python-basics-06-booleans-and-comparisons',
  E'Booleans and comparisons',
  E'Decisions in code come down to `True` or `False`.',
  E'Predict whether a comparison is True or False.',
  E'**Concept.** Comparisons return a boolean: `>` `<` `>=` `<=` `==` `!=`. Common mistake: `=` is assignment, `==` is comparison.\n\n**Example.**\n\n```python\nprint(5 > 3)    # True\nprint(5 == 5)   # True\nprint(5 != 4)   # True\nprint(5 < 3)    # False\n```\n\n**Predict.** What does this print?\n\n**Expected.** `True`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'booleans'],
  true,
  6
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000206',
  '00000000-0000-0000-0000-000000000021',
  'python-basics-07-if-elif-else',
  E'if elif else',
  E'`if` runs a block when a condition is true; `else` runs when it isn''t.',
  E'Pick one of two messages based on a comparison.',
  E'**Concept.** `if condition:` followed by an indented block. `elif` is "else if". `else` catches everything else. The `:` is required, and indentation (4 spaces) marks the block.\n\n**Example.**\n\n```python\nage = 18\nif age >= 18:\n    print("Adult")\nelse:\n    print("Kid")\n```\n\n**Your turn.** Fill in the comparison so the program prints `cold`.\n\n**Expected.** `cold`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'control-flow'],
  true,
  7
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000207',
  '00000000-0000-0000-0000-000000000021',
  'python-basics-08-logical-operators',
  E'Logical operators',
  E'Real conditions are usually combinations of smaller ones.',
  E'Predict the result of a compound boolean expression.',
  E'**Concept.** `and` — both sides must be true. `or` — at least one. `not` — flips True/False. Precedence: `not` > `and` > `or`; use parens when unsure.\n\n**Example.**\n\n```python\nprint(True and False)    # False\nprint(True or False)     # True\nprint(5 > 3 and 5 < 10)  # True\n```\n\n**Predict.** What does this print?\n\n**Expected.** `True`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'booleans'],
  true,
  8
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000208',
  '00000000-0000-0000-0000-000000000022',
  'python-basics-09-for-loops-with-range',
  E'for loops with range',
  E'When you want to do something a fixed number of times, `for i in range(n)` is idiomatic.',
  E'Use a `for` loop with `range()` to print numbers.',
  E'**Concept.** `range(n)` produces 0, 1, … n-1. `range(a, b)` produces a, a+1, … b-1 — it stops BEFORE `b`.\n\n**Example.**\n\n```python\nfor i in range(5):\n    print(i)\n# prints 0, 1, 2, 3, 4 (not 5)\n```\n\n**Your turn.** Print the numbers 1 through 5 inclusive.\n\n**Expected.** `1 · 2 · 3 · 4 · 5`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'loops'],
  true,
  9
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000209',
  '00000000-0000-0000-0000-000000000022',
  'python-basics-10-for-loops-over-lists',
  E'for loops over lists',
  E'`for` walks over any sequence — lists, strings, dictionaries — one item at a time.',
  E'Iterate over a list and print each item.',
  E'**Concept.** `for item in iterable:` binds `item` to each element in turn. The loop variable''s name is yours to choose; it should describe one element.\n\n**Example.**\n\n```python\nfruits = ["apple", "banana", "cherry"]\nfor fruit in fruits:\n    print(fruit)\n```\n\n**Your turn.** Fill in the loop variable so each name prints.\n\n**Expected.** `Ada · Linus · Grace`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'loops', 'lists'],
  true,
  10
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000020a',
  '00000000-0000-0000-0000-000000000022',
  'python-basics-11-while-loops',
  E'while loops',
  E'`while` runs as long as a condition is true. Use it when you don''t know in advance how many iterations.',
  E'Count down from 5 with a `while` loop.',
  E'**Concept.** The condition is checked at the TOP of each iteration. The loop must eventually make the condition false — otherwise it runs forever (the sandbox aborts at 200,000 steps with a clear error).\n\n**Example.**\n\n```python\ncount = 3\nwhile count > 0:\n    print(count)\n    count = count - 1\nprint("Go!")\n```\n\n**Your turn.** Fill in the operator so `count` shrinks each iteration.\n\n**Expected.** `5 · 4 · 3 · 2 · 1 · Go!`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'loops'],
  true,
  11
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000020b',
  '00000000-0000-0000-0000-000000000022',
  'python-basics-12-break-and-continue',
  E'break and continue',
  E'`break` exits a loop immediately. `continue` skips to the next iteration.',
  E'Predict the output of a loop that breaks early.',
  E'**Concept.** `break` jumps out of the enclosing loop right away — no more iterations. `continue` jumps back to the loop header for the next iteration, skipping the rest of the body.\n\n**Example.**\n\n```python\nfor i in range(5):\n    if i == 2:\n        continue   # skips 2\n    print(i)\n```\n\n**Predict.** What does this print?\n\n**Expected.** `0 · 2 · 4`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'loops'],
  true,
  12
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000020c',
  '00000000-0000-0000-0000-000000000023',
  'python-basics-13-lists',
  E'Lists',
  E'A list holds an ordered collection of values. Index from 0 to access them.',
  E'Read a specific element of a list by its index.',
  E'**Concept.** `my_list[0]` is the first element. `my_list[-1]` is the last. `my_list[a:b]` is a slice from index `a` (inclusive) to `b` (exclusive).\n\n**Example.**\n\n```python\ncolors = ["red", "green", "blue"]\nprint(colors[0])     # "red"\nprint(colors[-1])    # "blue"\n```\n\n**Your turn.** Print the second element of `scores`.\n\n**Expected.** `88`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'lists'],
  true,
  13
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000020d',
  '00000000-0000-0000-0000-000000000023',
  'python-basics-14-list-operations',
  E'List operations',
  E'Lists are mutable: you can grow them, sort them, and check what''s in them.',
  E'Append to a list and check its length.',
  E'**Concept.** `my_list.append(x)` adds `x` to the end (in-place). `len(my_list)` returns how many elements it has. `x in my_list` checks membership.\n\n**Example.**\n\n```python\nnumbers = [3, 1, 4]\nnumbers.append(1)\nprint(len(numbers))  # 4\n```\n\n**Your turn.** Append `"strawberry"` to `fruits`, then print its length.\n\n**Expected.** `3`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'lists'],
  true,
  14
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000020e',
  '00000000-0000-0000-0000-000000000023',
  'python-basics-15-dictionaries',
  E'Dictionaries',
  E'A dictionary maps keys to values — like a real-world index card.',
  E'Read a value from a dictionary by its key.',
  E'**Concept.** `my_dict[key]` retrieves the value stored under `key`. Keys are usually strings. Looking up a missing key raises `KeyError`.\n\n**Example.**\n\n```python\nuser = {"name": "Ada", "age": 36}\nprint(user["name"])  # Ada\n```\n\n**Your turn.** Print the value for the key `"capital"`.\n\n**Expected.** `Paris`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'dicts'],
  true,
  15
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000020f',
  '00000000-0000-0000-0000-000000000023',
  'python-basics-16-sets-and-tuples',
  E'Sets and tuples',
  E'A `set` is unordered and de-duplicates. A `tuple` is like a list but immutable.',
  E'Predict how many unique values are in a set.',
  E'**Concept.** `{1, 2, 2, 3}` becomes `{1, 2, 3}` — duplicates are removed. Sets are fast for membership checks. Tuples use `(...)`; their elements can''t change.\n\n**Example.**\n\n```python\nunique = {1, 2, 2, 3, 3, 3}\nprint(unique)  # {1, 2, 3}\n```\n\n**Predict.** What does this print?\n\n**Expected.** `3`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'sets', 'tuples'],
  true,
  16
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000210',
  '00000000-0000-0000-0000-000000000024',
  'python-basics-17-defining-functions',
  E'Defining functions',
  E'Functions give a name to a block of code so you can reuse it.',
  E'Define a function with `def` and call it.',
  E'**Concept.** `def name():` defines a function. The body is indented under it. `name()` calls it — and you can call it as many times as you like.\n\n**Example.**\n\n```python\ndef greet():\n    print("Hello!")\n\ngreet()\ngreet()\n```\n\n**Your turn.** Define `say_python` so calling it prints `Python rocks`, then call it twice.\n\n**Expected.** `Python rocks · Python rocks`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'functions'],
  true,
  17
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000211',
  '00000000-0000-0000-0000-000000000024',
  'python-basics-18-parameters',
  E'Parameters',
  E'Functions become useful when they take inputs.',
  E'Define a function with one parameter.',
  E'**Concept.** `def greet(name):` — `name` is a parameter. Inside the body it holds whatever value the caller passes. Defaults work too: `def greet(name="friend"):`.\n\n**Example.**\n\n```python\ndef greet(name):\n    print(f"Hello, {name}!")\n\ngreet("Ada")    # Hello, Ada!\n```\n\n**Your turn.** Add the parameter `name` so the function prints `Welcome, Grace`.\n\n**Expected.** `Welcome, Grace`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'functions'],
  true,
  18
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000212',
  '00000000-0000-0000-0000-000000000024',
  'python-basics-19-return-values',
  E'Return values',
  E'Most functions don''t just print — they compute and return a value the caller uses.',
  E'Write a function that returns its result.',
  E'**Concept.** `return expr` exits the function and sends `expr` back to the caller. The caller can store it (`x = f()`) or use it in an expression (`f() + 1`).\n\n**Example.**\n\n```python\ndef double(n):\n    return n * 2\n\nresult = double(7)\nprint(result)  # 14\n```\n\n**Your turn.** Fill in the return expression so `add(a, b)` returns their sum.\n\n**Expected.** `5 · 30`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'functions'],
  true,
  19
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000213',
  '00000000-0000-0000-0000-000000000024',
  'python-basics-20-local-vs-global-scope',
  E'Local vs global scope',
  E'Variables defined inside a function don''t exist outside it — that''s local scope.',
  E'Predict what each `print` outputs.',
  E'**Concept.** Assigning to a name inside a function creates a LOCAL variable. The global with the same name is hidden, not modified. The outer global keeps its old value when the function returns.\n\n**Example.**\n\n```python\nx = 10\ndef show():\n    x = 20  # local — different variable\n    print(x)\n\nshow()      # 20\nprint(x)    # 10\n```\n\n**Predict.** What does this print, one number per line?\n\n**Expected.** `100 · 5`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'functions', 'scope'],
  true,
  20
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000214',
  '00000000-0000-0000-0000-000000000025',
  'python-basics-21-try-and-except',
  E'try and except',
  E'Some operations fail at runtime (dividing by zero, missing dict keys). `try/except` lets you handle the failure.',
  E'Catch a `KeyError` so the program prints `unknown`.',
  E'**Concept.** `try:` runs its block. If an exception of a matching type is raised, control jumps to the matching `except`. The `except` keyword introduces the fallback.\n\n**Example.**\n\n```python\ntry:\n    result = 10 / 0\nexcept ZeroDivisionError:\n    result = "infinity"\nprint(result)  # infinity\n```\n\n**Your turn.** Replace `___` with the keyword that starts the fallback block.\n\n**Expected.** `unknown`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'errors'],
  true,
  21
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000215',
  '00000000-0000-0000-0000-000000000025',
  'python-basics-22-list-comprehensions',
  E'List comprehensions',
  E'List comprehensions build a new list by transforming each item — in one line.',
  E'Build a list of the squares of 1..5.',
  E'**Concept.** The shape is `[expr for item in iterable]`. You can add an `if`: `[n for n in nums if n > 0]`. It''s a compact replacement for a `for`-loop + `.append()` pattern.\n\n**Example.**\n\n```python\nnumbers = [1, 2, 3, 4]\ndoubled = [n * 2 for n in numbers]\nprint(doubled)  # [2, 4, 6, 8]\n```\n\n**Your turn.** Fill in the operator so the comprehension produces squares.\n\n**Expected.** `[1, 4, 9, 16, 25]`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'comprehensions'],
  true,
  22
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000216',
  '00000000-0000-0000-0000-000000000025',
  'python-basics-23-imports-and-the-standard-library',
  E'Imports and the standard library',
  E'Python comes with batteries included — `import` pulls a module in.',
  E'Import `math` and use one of its values.',
  E'**Concept.** `import math` makes the module available as `math`. Reach into it with a dot: `math.pi`, `math.sqrt(16)`. `from math import sqrt` imports just one name.\n\n**Example.**\n\n```python\nimport math\nprint(math.sqrt(16))  # 4.0\nprint(math.pi)        # 3.141592653589793\n```\n\n**Your turn.** Add the keyword that pulls `math` into the program.\n\n**Expected.** `3.14`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'imports'],
  true,
  23
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000217',
  '00000000-0000-0000-0000-000000000026',
  'python-basics-24-defining-classes',
  E'Defining classes',
  E'Classes bundle data and behaviour together — the foundation of object-oriented Python.',
  E'Complete a class''s constructor.',
  E'**Concept.** `__init__` is the constructor; it runs when you do `MyClass(...)`. `self` is the instance the method is called on. Attributes assigned to `self.x` are stored on the instance.\n\n**Example.**\n\n```python\nclass Dog:\n    def __init__(self, name):\n        self.name = name\n    def bark(self):\n        print(f"{self.name} says woof")\n```\n\n**Your turn.** Set `self.name = name` so `greet()` reads `self.name` correctly.\n\n**Expected.** `Hello from Python`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'classes'],
  true,
  24
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000218',
  '00000000-0000-0000-0000-000000000026',
  'python-basics-25-a-tiny-to-do-list',
  E'A tiny to-do list',
  E'Combine functions, lists, and dictionaries into a tiny to-do list.',
  E'Make `add_task` actually add a task to the list.',
  E'**Concept.** A task is a dict with keys `title` and `done`. `add_task(title, done=False)` should append a new dict to the global `tasks` list. The list method `.append(item)` adds `item` to the end.\n\n**Example.**\n\n```python\ntasks = []\ntasks.append({"title": "Learn Python", "done": False})\nprint(tasks[0]["title"])  # Learn Python\n```\n\n**Your turn.** Replace `___` with the list method that adds an item to the end.\n\n**Expected.** `- [ ] Learn Python · - [x] Drink coffee · - [ ] Write a function`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['python-basics', 'project'],
  true,
  25
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.skills (slug, name) values
  ('arithmetic', 'Arithmetic'),
  ('booleans', 'Booleans'),
  ('classes', 'Classes'),
  ('comprehensions', 'Comprehensions'),
  ('control-flow', 'Control flow'),
  ('dicts', 'Dictionaries'),
  ('errors', 'Error handling'),
  ('functions', 'Functions'),
  ('imports', 'Imports'),
  ('io', 'Input / output'),
  ('lists', 'Lists'),
  ('loops', 'Loops'),
  ('project', 'Mini-project'),
  ('python-basics', 'Python basics'),
  ('scope', 'Variable scope'),
  ('sets', 'Sets'),
  ('strings', 'Strings'),
  ('tuples', 'Tuples'),
  ('types', 'Type conversion'),
  ('variables', 'Variables')
on conflict (slug) do update set name = excluded.name;
