-- AUTO-GENERATED by scripts/generate_quant_projects.py
-- Quant track mini-project inserts.

delete from public.challenges where slug like 'quant-project-%';

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000340',
  '00000000-0000-0000-0000-000000000031',
  'quant-project-1-monte-carlo-asset-paths',
  E'Monte Carlo asset paths',
  E'Welcome to your first proper quant project. The Monte Carlo simulator you build here is the same engine — modulo a few performance tweaks — that every Bank''s exotic-options desk uses to price path-dependent structures, that every risk team uses to compute VaR via simulation, and that every research notebook at AQR or Citadel starts with when studying a new strategy''s path distribution.',
  E'Implement a GBM simulator and a terminal-distribution stats helper, then pass 8 tests that check shape, reproducibility, drift, variance scaling, and the percentile structure.',
  E'# Monte Carlo asset paths\n\nWelcome to the canonical "first quant project." Simulate many price\npaths under geometric Brownian motion (GBM), then study the resulting\ndistribution of terminal prices.\n\n## What you build\n\n- **`paths.py`** — `simulate_gbm(S0, mu, sigma, T, steps, paths, seed)`\n  returns a `(steps + 1, paths)` ndarray of price trajectories.\n- **`stats.py`** — `terminal_stats(prices)` returns the summary stats of\n  the final row: `{mean, std, p05, p95}`.\n\n## What the tests check\n\n- Shape, first-row-is-S0, reproducibility under a fixed seed\n- Zero-vol path matches `S0 * exp(mu * T)` exactly\n- Sample mean of `S_T` is within 2% of `S0 * exp(mu * T)` at 10k paths\n- Variance of `log(S_T / S0)` scales linearly with horizon\n- `terminal_stats` returns the four expected keys with the right ordering\n\n## References\n\n- Hilpisch, *Derivatives Analytics with Python* (dawp) —\n  github.com/yhilpisch/dawp\n- Glasserman, *Monte Carlo Methods in Financial Engineering* — the\n  textbook every quant has on their shelf\n\n## Time\n\n~60 minutes if you know GBM; ~2 hours from first principles.\n\n## Files in this project\n\n- `paths.py` (editable)\n- `stats.py` (editable)\n- `tests/test_paths.py` (read-only)\n- `tests/conftest.py` (read-only)\n- `README.md` (read-only)\n\n## How to run\n\nClick **Run tests** below — pytest discovers `tests/test_*.py` automatically. Failing tests light up red and the mentor on the right can explain what each assertion expects.',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": true}',
  array['quant', 'numpy', 'monte-carlo', 'random-numbers'],
  true,
  101
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;
