-- AUTO-GENERATED by scripts/generate_quant.py
-- Quant track challenge inserts. Track + modules live in
-- supabase/quant_programmer_seed.sql — apply that first.

delete from public.challenges where slug like 'quant-%';

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000300',
  '00000000-0000-0000-0000-000000000031',
  'quant-01-why-numpy',
  E'Why numpy',
  E'First morning at AQR. Your manager hands you a notebook with 7 years of minute-bar SPY data — 12 million rows — and wants a 10-day momentum signal by lunch. In pure Python the iteration would take 6 minutes per run; in numpy it''s 4 seconds. That gap is the whole reason quants live in numpy.',
  E'Measure the real speed gap between a Python sum and a numpy sum on a million numbers.',
  E'**Concept.** numpy arrays store fixed-size numbers contiguously in memory. A `.sum()` runs as one C loop with no Python interpreter overhead per element — typically 50-100× faster than the equivalent Python for-loop. The work being done is identical; the dispatch cost is what disappears.\n\n**Example.**\n\n```python\nimport numpy as np, time\nn = 1_000_000\nxs = list(range(n))\narr = np.arange(n)\n\nt0 = time.perf_counter()\ns1 = sum(xs)\nt1 = time.perf_counter()\ns2 = int(arr.sum())\nt2 = time.perf_counter()\n\nprint(f''loop:  {(t1-t0)*1e3:6.1f}ms'')\nprint(f''numpy: {(t2-t1)*1e3:6.1f}ms'')\nprint(''answers match:'', s1 == s2)\n```\n\n**Predict.** Both compute the same sum 0+1+…+999999. Predict the boolean result.\n\n**Expected.** `True`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'vectorisation'],
  true,
  1
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000301',
  '00000000-0000-0000-0000-000000000031',
  'quant-02-creating-arrays',
  E'Creating arrays',
  E'The Citadel research team''s morning ritual: load yesterday''s tape, slice it, line it up against a benchmark grid. Three constructors handle nearly every input you''ll ever build — `np.array` for known data, `np.zeros` for pre-allocated buffers, `np.linspace` for evenly-spaced sampling grids (the canonical y-axis builder for IV surfaces).',
  E'Use np.array, np.zeros, and np.linspace to build the three array shapes you''ll actually use.',
  E'**Concept.** `np.array([…])` lifts a Python list. `np.zeros(n)` pre-allocates `n` zeros — useful when you''ll fill values in a loop. `np.linspace(start, stop, n)` returns `n` evenly spaced points including both endpoints — used for plot grids and parameter sweeps.\n\n**Example.**\n\n```python\nimport numpy as np\n# A literal list — known coupon rates on three bonds.\ncoupons = np.array([0.025, 0.032, 0.041])\n# Pre-allocated buffer for tomorrow''s signals.\nsignals = np.zeros(252)\n# Evenly-spaced strikes for an IV surface — 80% to 120% of spot.\nstrikes = np.linspace(80, 120, 5)\nprint(coupons, signals[:3], strikes, sep='' | '')\n```\n\n**Your turn.** Fill the two blanks: zero-buffer for `signals`, evenly-spaced grid for `strikes`.\n\n**Expected.** `[0.025 0.032 0.041] | [0. 0. 0.] | [ 80.  90. 100. 110. 120.]`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy'],
  true,
  2
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000302',
  '00000000-0000-0000-0000-000000000031',
  'quant-03-broadcasting-basics',
  E'Broadcasting basics',
  E'Your strategy holds 4 positions on each of 3 days. You want to subtract the risk-free rate (a single 3-day vector) from every row of returns. Two for-loops? No. numpy''s broadcasting handles it as one expression — adds about a microsecond, regardless of how many positions you have.',
  E'Read a broadcast subtraction and predict the resulting first row.',
  E'**Concept.** When a `(3,)` vector meets a `(4, 3)` matrix, numpy implicitly stretches the vector along the missing axis — as if you''d repeated it four times. Shapes must align from the *trailing* axis. The big win is no temporary copies — the C loop just reuses the smaller buffer.\n\n**Example.**\n\n```python\nimport numpy as np\n# 4 positions × 3 days of raw daily returns.\nraw = np.full((4, 3), 0.012)\n# Risk-free rate per day (3-vector).\nrf = np.array([0.0001, 0.0001, 0.0002])\nexcess = raw - rf\nprint(excess[0])\n```\n\n**Predict.** Predict the first row of `excess` — the 4-position raw returns minus the 3-day risk-free vector.\n\n**Expected.** `[0.0119 0.0119 0.0118]`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'vectorisation'],
  true,
  3
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000303',
  '00000000-0000-0000-0000-000000000031',
  'quant-04-broadcasting-gotchas',
  E'Broadcasting gotchas',
  E'Most numpy errors a junior research engineer raises are shape mismatches. Take 30 seconds to learn what ''can''t broadcast (4,) with (4, 3)'' actually means — then you''ll fix it in 30 seconds instead of 30 minutes.',
  E'Recognise when shapes do not align and how to reshape to make them.',
  E'**Concept.** Broadcasting aligns dimensions from the *right*. A `(4,)` vector vs a `(4, 3)` matrix doesn''t align — the trailing dimensions are 4 and 3. Reshape the vector to `(4, 1)` (a column) and now the trailing dimensions are 1 and 3 — broadcastable, because size-1 axes stretch.\n\n**Example.**\n\n```python\nimport numpy as np\nraw = np.full((4, 3), 0.01)\nweights = np.array([1.0, 0.5, 2.0, 1.5])  # one per position\n# This would fail: raw - weights  (shapes (4,3) vs (4,) — won''t align)\n# Reshape to a column so each row of `raw` gets its own weight:\nscaled = raw * weights.reshape(4, 1)\nprint(scaled[:, 0])\n```\n\n**Predict.** `scaled` is shape (4, 3) with each row multiplied by its weight. Predict its first column.\n\n**Expected.** `[0.01  0.005 0.02  0.015]`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'vectorisation'],
  true,
  4
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000304',
  '00000000-0000-0000-0000-000000000031',
  'quant-05-boolean-masks',
  E'Boolean masks',
  E'You''re scanning a day of NYSE trade prints for outliers — anything more than 2 standard deviations above the running mean. The pure-Python way: a for-loop with an if. The numpy way: one comparison, one indexing operation, no loop. Every research desk uses this pattern daily.',
  E'Filter an array of returns to keep only the strictly-positive entries.',
  E'**Concept.** `arr > 0` returns a boolean array of the same shape. Using it as an index (`arr[mask]`) keeps just the True entries. The comparison and indexing run in C — no Python iteration. This pattern scales: replace `> 0` with `> 2 * arr.std()` for outlier detection.\n\n**Example.**\n\n```python\nimport numpy as np\n# Six minutes of mid-quote returns.\nr = np.array([-0.02, 0.01, -0.005, 0.015, 0.0, 0.03])\n# Keep only minutes the price strictly went up.\nup_only = r[r > 0]\nprint(up_only)\nprint(f''kept {len(up_only)} of {len(r)} minutes'')\n```\n\n**Your turn.** Replace `___` with the operator that keeps strictly-positive returns only.\n\n**Expected.** `[0.01  0.015 0.03 ] · kept 3 of 6 minutes`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'vectorisation'],
  true,
  5
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000305',
  '00000000-0000-0000-0000-000000000031',
  'quant-06-variance-from-scratch',
  E'Variance from scratch',
  E'Before you reach for `arr.var()`, derive it once. Variance is the mean of squared deviations from the mean — three ops in numpy. Doing this by hand once is what makes a covariance matrix obvious later.',
  E'Compute variance from the definition, without using `.var()`, and verify against numpy''s built-in.',
  E'**Concept.** Variance σ² = mean((x - μ)²). In numpy: take the deviations (`x - x.mean()`), square them (`** 2`), take the mean. That''s it. The square is elementwise broadcasting; the mean is a single reduction.\n\n**Example.**\n\n```python\nimport numpy as np\nrng = np.random.default_rng(0)\nx = rng.normal(loc=0.0, scale=0.02, size=10_000)\n\n# By hand — the textbook formula.\nmu = x.mean()\ndeviations = x - mu\nvar_manual = (deviations ** 2).mean()\n\n# Sanity-check against numpy.\nprint(round(var_manual, 6), round(x.var(), 6))\nprint(np.isclose(var_manual, x.var()))\n```\n\n**Your turn.** Replace `___` with the operator that elementwise-squares the deviations.\n\n**Expected.** `0.000398 0.000398 · True`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'statistics'],
  true,
  6
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000306',
  '00000000-0000-0000-0000-000000000031',
  'quant-07-covariance-via-matrix-algebra',
  E'Covariance via matrix algebra',
  E'Covariance between asset returns underpins everything in portfolio construction — Sharpe, Markowitz, principal components. The textbook formula `(X − μ)ᵀ(X − μ) / n` is one line in numpy and the building block of every Risk Engine you''ll ever work on.',
  E'Compute a 2×2 covariance matrix from two return series using matrix multiplication.',
  E'**Concept.** Stack two demeaned return series as columns of `X` (shape `(n, 2)`). Then `Xᵀ X / n` is the 2×2 covariance matrix. The diagonal is each series'' variance; the off-diagonals are the covariance. The matrix product runs as one BLAS call — fastest possible.\n\n**Example.**\n\n```python\nimport numpy as np\nrng = np.random.default_rng(0)\n# 1000 days of returns for two synthetic assets, independent.\nX = rng.normal(size=(1000, 2))\n# Demean each column before the dot product.\nXd = X - X.mean(axis=0)\ncov = Xd.T @ Xd / X.shape[0]\nprint(np.round(cov, 2))\n```\n\n**Your turn.** Replace `___` with the attribute that transposes the matrix.\n\n**Expected.** `[[ 1.04 -0.02] ·  [-0.02  0.96]]`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'linear-algebra', 'statistics'],
  true,
  7
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000307',
  '00000000-0000-0000-0000-000000000031',
  'quant-08-reproducible-random-numbers',
  E'Reproducible random numbers',
  E'Two Sigma''s research review board will reject a backtest that can''t be reproduced bit-for-bit. Every random draw in a research notebook gets a seed — usually a module-level constant, sometimes per-experiment. Reproducibility is non-negotiable.',
  E'Seed two generators with the same value and confirm they produce identical draws.',
  E'**Concept.** `np.random.default_rng(seed)` returns a Generator object. Same seed → same draws, every time. The legacy `np.random.seed(...)` global is fine for scripts but `default_rng` is the modern, thread-safe API — use it.\n\n**Example.**\n\n```python\nimport numpy as np\n# Two researchers, same seed, must get the same sample.\nalice = np.random.default_rng(42).normal(size=3)\nbob   = np.random.default_rng(42).normal(size=3)\nprint(''alice:'', alice)\nprint(''bob:  '', bob)\nprint(''identical:'', np.array_equal(alice, bob))\n```\n\n**Your turn.** Replace `___` so both generators draw the same sequence.\n\n**Expected.** `alice: [ 0.30471708 -1.03998411  0.7504512 ] · bob:   [ 0.30471708 -1.03998411  0.7504512 ] · identical: True`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'random-numbers'],
  true,
  8
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000308',
  '00000000-0000-0000-0000-000000000031',
  'quant-09-statistical-reductions',
  E'Statistical reductions',
  E'Every research note ends with a one-liner: ''over the period, mean daily return was X bps with σ = Y bps, 95th percentile drawdown Z.'' Three reductions, one line, the whole story.',
  E'Compute the mean, standard deviation, and 95th percentile of a 10k-sample return distribution.',
  E'**Concept.** numpy reductions take an axis (default: whole array). `arr.mean()` and `arr.std()` are methods; `np.percentile(arr, q)` is a function — `q` is in 0–100, NOT 0–1. They all run in C under the hood; on a million points each takes microseconds.\n\n**Example.**\n\n```python\nimport numpy as np\nrng = np.random.default_rng(0)\n# 10k daily returns from a slightly-positive-drift, 2%-vol distribution.\nr = rng.normal(loc=0.001, scale=0.02, size=10_000)\n\nmu    = r.mean()\nsigma = r.std()\np95   = np.percentile(r, 95)\n\nprint(f''mean  = {mu:.4f}'')\nprint(f''std   = {sigma:.4f}'')\nprint(f''p95   = {p95:.4f}'')\n```\n\n**Your turn.** Fill the three blanks with the reduction names: average, standard deviation, percentile.\n\n**Expected.** `mean  = 0.0011 · std   = 0.0200 · p95   = 0.0338`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'statistics'],
  true,
  9
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000309',
  '00000000-0000-0000-0000-000000000031',
  'quant-10-why-numpy-is-fast',
  E'Why numpy is fast',
  E'numpy isn''t magic. It''s a thin Python skin over carefully-optimised C and BLAS libraries written over 30 years. When you call `arr.sum()`, what runs is roughly 8 lines of C with SIMD intrinsics. When you write a Python `for` loop, what runs is 1 million dispatches through the interpreter. Hence the gap.',
  E'Run a sum of one million elements and recognise the printed value.',
  E'**Concept.** numpy stores arrays as contiguous C buffers and runs ufuncs as tight C loops with no per-element Python overhead. The same loop in pure Python pays interpreter overhead per iteration — 50-100× slower. Open one of numpy''s C-level source files some weekend — they''re surprisingly readable.\n\n**Example.**\n\n```python\nimport numpy as np\nx = np.arange(1_000_000)\n# Sum 0 + 1 + 2 + ... + 999999.\n# In numpy: one C loop, no per-element Python overhead.\n# In Python: 1,000,000 trips through the interpreter.\nprint(int(x.sum()))\n```\n\n**Predict.** Predict the printed sum of 0..999999. (Hint: n(n−1)/2 with n = 1,000,000.)\n\n**Expected.** `499999500000`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'performance'],
  true,
  10
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000030a',
  '00000000-0000-0000-0000-000000000031',
  'quant-11-the-slow-python-rolling-mean',
  E'The slow Python rolling-mean',
  E'A junior at a prop shop writes a 30-day rolling mean as a Python double-loop. The desk''s nightly batch goes from 4 minutes to 28. Senior glares. Tomorrow''s lesson is `np.cumsum` — today, FEEL the slow path so you''ll never write it.',
  E'Read the naive Python rolling-mean loop and predict its output on a small input.',
  E'**Concept.** The naive rolling mean iterates outer × window times. For 100k points and window 30: 3 million Python operations. Same answer as numpy, but ~200× slower. The fix is the cumulative-sum trick (next lesson). First, see what it replaces.\n\n**Example.**\n\n```python\nx = [1, 2, 3, 4, 5, 6]\nw = 3\nrolling = []\nfor i in range(w - 1, len(x)):\n    # Inner loop: w Python ops per output row.\n    s = 0\n    for j in range(i - w + 1, i + 1):\n        s += x[j]\n    rolling.append(s / w)\nprint(rolling)\n```\n\n**Predict.** Predict the printed list of rolling means.\n\n**Expected.** `[2.0, 3.0, 4.0, 5.0]`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'performance'],
  true,
  11
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000030b',
  '00000000-0000-0000-0000-000000000031',
  'quant-12-vectorising-with-cumsum',
  E'Vectorising with cumsum',
  E'Same answer as yesterday''s double-loop, ~200× faster. The cumulative-sum trick — `c[i] − c[i−w]` — is one of the most useful identities in numerical Python. Every senior quant carries it in their head; you should too.',
  E'Replace the Python rolling-mean loop with `np.cumsum`.',
  E'**Concept.** If `c = cumsum(x)`, then the window-`w` sum ending at index `i` equals `c[i] − c[i−w]`. Prepend a zero to `c` so the slice arithmetic is clean. One pass, no inner loop, all in C. The same trick gives you rolling sums of any cost function — drawdowns, exposures, anything.\n\n**Example.**\n\n```python\nimport numpy as np\nx = np.array([1, 2, 3, 4, 5, 6], dtype=float)\nw = 3\n# Prepend 0 so c[w:] - c[:-w] gives clean window sums.\nc = np.concatenate(([0], np.cumsum(x)))\nrolling = (c[w:] - c[:-w]) / w\nprint(rolling)\n```\n\n**Your turn.** Replace `___` with the cumulative-sum function.\n\n**Expected.** `[2. 3. 4. 5.]`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'vectorisation', 'performance'],
  true,
  12
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000030c',
  '00000000-0000-0000-0000-000000000031',
  'quant-13-plot-a-price-path',
  E'Plot a price path',
  E'Every research note ships with a chart. The first one''s always the same: simulate a price path, plot it, label axes, title. Get that muscle memory and the rest of matplotlib is just more of the same.',
  E'Simulate a geometric Brownian motion price path and plot it with labelled axes.',
  E'**Concept.** GBM in one line: `price = S0 * exp(cumsum(shocks))`. `plt.plot(price)` draws the line; `plt.xlabel`, `plt.ylabel`, `plt.title` annotate it. matplotlib''s pyplot API mirrors MATLAB — one statement per directive, which makes it easy to read in code review.\n\n**Example.**\n\n```python\nimport numpy as np, matplotlib.pyplot as plt\nrng = np.random.default_rng(0)\n# 252 trading days of small daily shocks (~1% daily vol).\nshocks = rng.normal(0, 0.01, 252)\n# GBM: log-returns sum, prices are the exp.\nprice = 100 * np.exp(np.cumsum(shocks))\nplt.plot(price)\nplt.title(''Simulated price path'')\nplt.xlabel(''trading day'')\nplt.ylabel(''price (USD)'')\nprint(''plotted'')\n```\n\n**Your turn.** Replace `___` with the variable holding the price series.\n\n**Expected.** `plotted`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'matplotlib', 'monte-carlo'],
  true,
  13
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000030d',
  '00000000-0000-0000-0000-000000000032',
  'quant-14-dataframes-from-csv',
  E'DataFrames from CSV',
  E'A DataFrame is the workhorse of every research notebook. Loading 10 years of SPY prices takes one call.',
  E'Load the bundled SPY CSV into a DataFrame and report its shape.',
  E'**Concept.** `pd.read_csv(path)` returns a DataFrame. `df.shape` gives `(rows, cols)`. The bundled file `/data/quant/spy.csv` has daily OHLCV bars 2015–2025.\n\n**Example.**\n\n```python\nimport pandas as pd\ndf = pd.read_csv(''/data/quant/spy.csv'')\nprint(df.shape)\n```\n\n**Your turn.** Fill in the pandas function that reads a CSV.\n\n**Expected.** `(2766, 7)`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'pandas'],
  true,
  14
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000030e',
  '00000000-0000-0000-0000-000000000032',
  'quant-15-loc-versus-iloc',
  E'Loc versus iloc',
  E'`.loc` indexes by label, `.iloc` indexes by position. Mixing them up is the most common pandas bug.',
  E'Predict the values returned by .iloc and .loc on a small frame.',
  E'**Concept.** `.iloc[0]` is always the first row. `.loc[0]` is the row labelled `0` — usually the same, until you sort or filter, then the label and the position diverge.\n\n**Example.**\n\n```python\nimport pandas as pd\ndf = pd.DataFrame({''price'': [100, 101, 99]}, index=[''a'', ''b'', ''c''])\nprint(df.iloc[0][''price''], df.loc[''b'', ''price''])\n```\n\n**Predict.** Predict what the print statement outputs.\n\n**Expected.** `100 101`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'pandas'],
  true,
  15
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000030f',
  '00000000-0000-0000-0000-000000000032',
  'quant-16-boolean-filtering-on-real-prices',
  E'Boolean filtering on real prices',
  E'`(df[''close''] > df[''open''])` returns a boolean Series. Pass it to `df[...]` and you''ve filtered the frame — vectorised, fast, idiomatic.',
  E'Count the SPY days where the close was above the open.',
  E'**Concept.** A comparison between two Series returns a boolean Series the same length. Using it as `df[mask]` keeps only rows where the mask is True. The number of up-days is `mask.sum()`.\n\n**Example.**\n\n```python\nimport pandas as pd\ndf = pd.read_csv(''/data/quant/spy.csv'')\nup = (df[''close''] > df[''open'']).sum()\nprint(up)\n```\n\n**Your turn.** Replace `___` with the operator that counts strictly-up days.\n\n**Expected.** `1487`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'pandas', 'vectorisation'],
  true,
  16
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000310',
  '00000000-0000-0000-0000-000000000032',
  'quant-17-daily-and-log-returns',
  E'Daily and log returns',
  E'Two ways to express returns: simple `(p_t / p_{t-1}) - 1` and log `ln(p_t / p_{t-1})`. They''re nearly identical for small moves and additively neat for the log version.',
  E'Compute simple and log returns from SPY adj_close and plot a histogram of each.',
  E'**Concept.** `series.pct_change()` is the simple return. Log returns are `np.log(p / p.shift(1))`. Plot histograms with `plt.hist(series.dropna(), bins=50)`.\n\n**Example.**\n\n```python\nimport pandas as pd, numpy as np, matplotlib.pyplot as plt\ndf = pd.read_csv(''/data/quant/spy.csv'')\nsimple = df[''adj_close''].pct_change().dropna()\nlog_r = np.log(df[''adj_close''] / df[''adj_close''].shift(1)).dropna()\nplt.hist(log_r, bins=60)\nplt.title(''SPY log returns''); plt.xlabel(''return''); plt.ylabel(''count'')\nprint(round(simple.std(), 4), round(log_r.std(), 4))\n```\n\n**Your turn.** Replace `___` with the pandas method that gives the simple return.\n\n**Expected.** `0.0112 0.0112`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'pandas', 'time-series', 'statistics'],
  true,
  17
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000311',
  '00000000-0000-0000-0000-000000000032',
  'quant-18-rolling-volatility',
  E'Rolling volatility',
  E'A 30-day rolling standard deviation of returns, annualised, is the canonical ''realised vol'' a strategy gates on.',
  E'Compute SPY''s 30-day rolling vol and plot it against time.',
  E'**Concept.** `r.rolling(window).std()` is the rolling std. Annualise daily vol with `* np.sqrt(252)`. The first 29 rows are NaN — that''s expected.\n\n**Example.**\n\n```python\nimport pandas as pd, numpy as np, matplotlib.pyplot as plt\ndf = pd.read_csv(''/data/quant/spy.csv'')\nr = df[''adj_close''].pct_change()\nvol = r.rolling(30).std() * np.sqrt(252)\nplt.plot(vol)\nplt.title(''SPY 30-day rolling vol''); plt.xlabel(''day''); plt.ylabel(''annualised vol'')\nprint(round(vol.max(), 3))\n```\n\n**Your turn.** Replace `___` with the reduction that gives standard deviation.\n\n**Expected.** `0.821`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'pandas', 'time-series', 'statistics'],
  true,
  18
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000312',
  '00000000-0000-0000-0000-000000000032',
  'quant-19-groupby-year',
  E'Groupby year',
  E'Pandas groupby is split-apply-combine. Group by calendar year and you can answer ''how did each year score?'' in two lines.',
  E'Compute SPY''s mean daily return by calendar year.',
  E'**Concept.** `pd.to_datetime(df[''date'']).dt.year` extracts the year. `df.groupby(year_series)[''adj_close''].pct_change().mean()` then averages within each group. Use `.agg(...)` or a single reduction.\n\n**Example.**\n\n```python\nimport pandas as pd\ndf = pd.read_csv(''/data/quant/spy.csv'')\ndf[''year''] = pd.to_datetime(df[''date'']).dt.year\nby_year = df.groupby(''year'')[''adj_close''].apply(lambda s: s.pct_change().mean())\nprint(round(by_year[2020], 5))\n```\n\n**Your turn.** Replace `___` with the pandas split-apply-combine method.\n\n**Expected.** `0.00085`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'pandas', 'time-series'],
  true,
  19
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000313',
  '00000000-0000-0000-0000-000000000032',
  'quant-20-aligning-two-series',
  E'Aligning two series',
  E'Real research mixes tickers with different calendars (BTC trades weekends; SPY doesn''t). Aligning on a shared index is the first step of any cross-asset analysis.',
  E'Merge SPY and AAPL on the date column and confirm row count.',
  E'**Concept.** `pd.merge(a, b, on=''date'', how=''inner'')` keeps rows where both have data. The result has all the columns of both frames, suffixed `_x` and `_y` when names collide.\n\n**Example.**\n\n```python\nimport pandas as pd\nspy = pd.read_csv(''/data/quant/spy.csv'')\naapl = pd.read_csv(''/data/quant/aapl.csv'')\njoined = pd.merge(spy, aapl, on=''date'', how=''inner'', suffixes=(''_spy'', ''_aapl''))\nprint(joined.shape)\n```\n\n**Your turn.** Replace `___` with the join type that keeps only common dates.\n\n**Expected.** `(2766, 13)`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'pandas', 'time-series'],
  true,
  20
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000314',
  '00000000-0000-0000-0000-000000000032',
  'quant-21-fitting-a-normal-to-returns',
  E'Fitting a normal to returns',
  E'Daily returns look gaussian-ish until you check the tails. Plotting a normal pdf over the empirical histogram makes the mismatch visible.',
  E'Fit a normal to SPY''s daily returns and overlay it on the histogram.',
  E'**Concept.** `scipy.stats.norm.fit(data)` returns `(mu, sigma)`. Generate the pdf with `norm.pdf(xs, mu, sigma)` and overlay with `plt.plot(xs, pdf)`. Set `plt.hist(..., density=True)` so the histogram is on the same scale.\n\n**Example.**\n\n```python\nimport pandas as pd, numpy as np, matplotlib.pyplot as plt\nfrom scipy.stats import norm\ndf = pd.read_csv(''/data/quant/spy.csv'')\nr = df[''adj_close''].pct_change().dropna()\nmu, sigma = norm.fit(r)\nxs = np.linspace(r.min(), r.max(), 200)\nplt.hist(r, bins=80, density=True, alpha=0.6)\nplt.plot(xs, norm.pdf(xs, mu, sigma))\nplt.title(''SPY daily returns vs normal fit'')\nprint(round(sigma, 4))\n```\n\n**Your turn.** Replace `___` with scipy''s MLE call.\n\n**Expected.** `0.0112`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'pandas', 'statistics'],
  true,
  21
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000315',
  '00000000-0000-0000-0000-000000000032',
  'quant-22-ols-beta-of-aapl-on-spy',
  E'OLS beta of AAPL on SPY',
  E'Beta of a single stock to the market is the simplest factor regression. statsmodels reports an inference summary — coefficient, std error, p-value, R².',
  E'Run OLS of AAPL returns on SPY returns and read the slope coefficient.',
  E'**Concept.** `statsmodels.api.OLS(y, X).fit()` returns a result. `X` must include a constant (use `sm.add_constant`). `.params` is the coefficient vector; the slope is index 1.\n\n**Example.**\n\n```python\nimport pandas as pd, statsmodels.api as sm\nspy = pd.read_csv(''/data/quant/spy.csv'')[''adj_close''].pct_change()\naapl = pd.read_csv(''/data/quant/aapl.csv'')[''adj_close''].pct_change()\ndf = pd.concat([spy, aapl], axis=1).dropna()\nX = sm.add_constant(df.iloc[:, 0])\nres = sm.OLS(df.iloc[:, 1], X).fit()\nprint(round(res.params.iloc[1], 2))\n```\n\n**Your turn.** Replace `___` with the linear-regression constructor.\n\n**Expected.** `1.21`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'pandas', 'statistics', 'regression'],
  true,
  22
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000316',
  '00000000-0000-0000-0000-000000000032',
  'quant-23-stationarity-preview',
  E'Stationarity preview',
  E'An ARIMA model needs stationary input. The Augmented Dickey-Fuller test gives a p-value: small p → reject ''unit root'' → series is stationary.',
  E'Read an ADF p-value on SPY prices vs returns and predict which is stationary.',
  E'**Concept.** `statsmodels.tsa.stattools.adfuller(s)` returns a tuple; element `[1]` is the p-value. Price series usually have p ≈ 1 (random walk, non-stationary); returns usually have p << 0.05.\n\n**Example.**\n\n```python\nimport pandas as pd\nfrom statsmodels.tsa.stattools import adfuller\ndf = pd.read_csv(''/data/quant/spy.csv'')\np_price = adfuller(df[''adj_close''])[1]\np_ret = adfuller(df[''adj_close''].pct_change().dropna())[1]\nprint(p_price > 0.05, p_ret < 0.05)\n```\n\n**Predict.** Predict the two booleans. The first asks ''is prices non-stationary?''; the second asks ''are returns stationary?''.\n\n**Expected.** `True True`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'pandas', 'time-series', 'statistics'],
  true,
  23
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000317',
  '00000000-0000-0000-0000-000000000033',
  'quant-24-present-value-of-a-single-cash-flow',
  E'Present value of a single cash flow',
  E'A pound tomorrow is worth less than a pound today. Discounting is the simplest version of every pricing model in finance.',
  E'Compute the present value of £1000 received in 5 years at a 4% discount rate.',
  E'**Concept.** `PV = CF / (1 + r)**t` for a single cash flow. With continuous compounding the formula is `PV = CF * exp(-r*t)`. Either is fine; pick the one the textbook is using.\n\n**Example.**\n\n```python\ncf, r, t = 1000, 0.04, 5\npv = cf / (1 + r)**t\nprint(round(pv, 2))\n```\n\n**Your turn.** Replace `___` with the Python exponentiation operator.\n\n**Expected.** `821.93`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'options'],
  true,
  24
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000318',
  '00000000-0000-0000-0000-000000000033',
  'quant-25-bond-yield-to-maturity',
  E'Bond yield to maturity',
  E'The YTM of a bond is the rate `r` that makes the discounted cash flows equal the price. There''s no closed-form solution — you solve it numerically.',
  E'Find the YTM of a 5-year bond paying a 5% coupon, priced at par (face=100).',
  E'**Concept.** The price of an annual-coupon bond is `sum(c / (1+r)**t for t in 1..N) + face / (1+r)**N`. When the bond trades at par, YTM equals the coupon rate by definition. `scipy.optimize.brentq` finds the root.\n\n**Example.**\n\n```python\nfrom scipy.optimize import brentq\nface, coupon, n, price = 100, 5, 5, 100\ndef npv(r):\n    return sum(coupon / (1+r)**t for t in range(1, n+1)) + face / (1+r)**n - price\nytm = brentq(npv, 0.0001, 0.5)\nprint(round(ytm, 4))\n```\n\n**Your turn.** Replace `___` with the root-finder we imported.\n\n**Expected.** `0.05`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'options'],
  true,
  25
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000319',
  '00000000-0000-0000-0000-000000000033',
  'quant-26-option-payoff-diagrams',
  E'Option payoff diagrams',
  E'A call''s payoff at expiry is `max(S - K, 0)`. A put''s is `max(K - S, 0)`. Plot them and you''ve drawn every derivatives textbook''s first figure.',
  E'Plot the payoff of a long call with strike 100 over spot prices 60..140.',
  E'**Concept.** `np.maximum(S - K, 0)` is the vectorised call payoff. Subtract the premium to get profit. `plt.plot(S, payoff)` does the rest.\n\n**Example.**\n\n```python\nimport numpy as np, matplotlib.pyplot as plt\nS = np.linspace(60, 140, 81)\nK, premium = 100, 5\npayoff = np.maximum(S - K, 0) - premium\nplt.plot(S, payoff)\nplt.title(''Long call (K=100)''); plt.xlabel(''spot''); plt.ylabel(''profit'')\nplt.axhline(0, color=''gray'', lw=0.5)\nprint(round(payoff[-1], 1))\n```\n\n**Your turn.** Replace `___` with the elementwise max function.\n\n**Expected.** `35.0`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'options', 'matplotlib'],
  true,
  26
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000031a',
  '00000000-0000-0000-0000-000000000033',
  'quant-27-put-call-parity',
  E'Put-call parity',
  E'Put-call parity says `C - P = S - K * exp(-r*T)`. It''s a no-arbitrage identity — if it breaks, someone is leaving money on the table.',
  E'Verify put-call parity numerically using the Black-Scholes prices.',
  E'**Concept.** From parity, given a call price, the matching put is `P = C - S + K * exp(-r*T)`. Compute both sides and they should match to machine precision.\n\n**Example.**\n\n```python\nimport numpy as np\nS, K, r, T, C = 100, 100, 0.04, 1.0, 9.6\nP_from_parity = C - S + K * np.exp(-r * T)\nprint(round(P_from_parity, 2))\n```\n\n**Your turn.** Replace `___` so the discount factor is correct (negative rate times time).\n\n**Expected.** `5.68`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'options'],
  true,
  27
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000031b',
  '00000000-0000-0000-0000-000000000033',
  'quant-28-black-scholes-from-scratch',
  E'Black-Scholes from scratch',
  E'The Black-Scholes call price is `S*N(d1) - K*exp(-r*T)*N(d2)` where `d1 = (ln(S/K) + (r + σ²/2)*T) / (σ*sqrt(T))` and `d2 = d1 - σ*sqrt(T)`.',
  E'Implement the Black-Scholes call price and verify against a textbook example.',
  E'**Concept.** `scipy.stats.norm.cdf` is N(). Hull''s example: S=100, K=100, r=5%, σ=20%, T=1 gives C ≈ 10.45. Match it.\n\n**Example.**\n\n```python\nimport numpy as np\nfrom scipy.stats import norm\nS, K, r, sigma, T = 100, 100, 0.05, 0.20, 1.0\nd1 = (np.log(S/K) + (r + sigma**2/2)*T) / (sigma*np.sqrt(T))\nd2 = d1 - sigma*np.sqrt(T)\nC = S*norm.cdf(d1) - K*np.exp(-r*T)*norm.cdf(d2)\nprint(round(C, 4))\n```\n\n**Your turn.** Fill the two blanks with the normal CDF function.\n\n**Expected.** `10.4506`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'options', 'black-scholes'],
  true,
  28
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000031c',
  '00000000-0000-0000-0000-000000000033',
  'quant-29-greeks-delta-of-a-call',
  E'Greeks: delta of a call',
  E'Delta is `dC/dS` — how much the option price moves when the underlying moves £1. For a Black-Scholes call, delta is just `N(d1)`.',
  E'Compute the delta of an at-the-money call.',
  E'**Concept.** From the BS derivation, `Δ_call = N(d1)`. For an at-the-money option (S=K), d1 ≈ 0.35 at typical parameters, so delta ≈ 0.64.\n\n**Example.**\n\n```python\nimport numpy as np\nfrom scipy.stats import norm\nS, K, r, sigma, T = 100, 100, 0.05, 0.20, 1.0\nd1 = (np.log(S/K) + (r + sigma**2/2)*T) / (sigma*np.sqrt(T))\ndelta = norm.cdf(d1)\nprint(round(delta, 4))\n```\n\n**Your turn.** Replace `___` with the scipy.stats object we imported.\n\n**Expected.** `0.6368`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'options', 'greeks'],
  true,
  29
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000031d',
  '00000000-0000-0000-0000-000000000033',
  'quant-30-binomial-tree-pricer',
  E'Binomial tree pricer',
  E'The CRR (Cox-Ross-Rubinstein) tree builds N steps of up/down moves and prices the option by backward induction. With enough steps it converges to Black-Scholes.',
  E'Price a European call with a 50-step binomial tree.',
  E'**Concept.** Set `u = exp(σ * sqrt(dt))`, `d = 1/u`, risk-neutral probability `p = (exp(r*dt) - d)/(u - d)`. Build terminal payoffs, then walk back to t=0 discounting at each step.\n\n**Example.**\n\n```python\nimport numpy as np\nS, K, r, sigma, T, N = 100, 100, 0.05, 0.20, 1.0, 50\ndt = T/N; u = np.exp(sigma*np.sqrt(dt)); d = 1/u\np = (np.exp(r*dt) - d)/(u - d)\nST = S * u**np.arange(N+1) * d**(N - np.arange(N+1))\nvals = np.maximum(ST - K, 0)\nfor _ in range(N):\n    vals = np.exp(-r*dt) * (p*vals[1:] + (1-p)*vals[:-1])\nprint(round(vals[0], 4))\n```\n\n**Your turn.** Replace `___` with the slice that gives ''all but the last'' (the down-branch values).\n\n**Expected.** `10.4107`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'options', 'black-scholes'],
  true,
  30
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000031e',
  '00000000-0000-0000-0000-000000000033',
  'quant-31-monte-carlo-option-pricing',
  E'Monte Carlo option pricing',
  E'Simulate many terminal stock prices under risk-neutral dynamics; average the discounted payoffs. The estimate converges as `1 / sqrt(N)` — plot to see it.',
  E'Price a European call by Monte Carlo and plot the running estimate''s convergence.',
  E'**Concept.** Under risk-neutral GBM, `S_T = S0 * exp((r - σ²/2)*T + σ*sqrt(T)*Z)` with `Z ~ N(0,1)`. Average `exp(-r*T) * max(S_T - K, 0)`. As N grows, the running mean settles on the BS price.\n\n**Example.**\n\n```python\nimport numpy as np, matplotlib.pyplot as plt\nS0, K, r, sigma, T, N = 100, 100, 0.05, 0.20, 1.0, 50_000\nrng = np.random.default_rng(0)\nZ = rng.standard_normal(N)\nST = S0 * np.exp((r - sigma**2/2)*T + sigma*np.sqrt(T)*Z)\npayoffs = np.exp(-r*T) * np.maximum(ST - K, 0)\nrunning = np.cumsum(payoffs) / np.arange(1, N+1)\nplt.plot(running)\nplt.axhline(10.4506, color=''red'', lw=0.5, label=''Black-Scholes'')\nplt.legend(); plt.title(''MC call price convergence'')\nprint(round(running[-1], 3))\n```\n\n**Your turn.** Replace `___` so the running mean accumulates correctly.\n\n**Expected.** `10.48`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'options', 'monte-carlo'],
  true,
  31
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000031f',
  '00000000-0000-0000-0000-000000000033',
  'quant-32-mean-variance-frontier',
  E'Mean-variance frontier',
  E'Markowitz''s efficient frontier is the locus of minimum-variance portfolios for each target return. Plot it for SPY + AAPL + TLT and you''ve recreated the most-cited chart in finance.',
  E'Sweep target returns and plot the resulting min-variance volatilities.',
  E'**Concept.** With covariance `Σ` and means `μ`, the closed-form min-variance frontier uses constants `a = 1ᵀΣ⁻¹1`, `b = μᵀΣ⁻¹1`, `c = μᵀΣ⁻¹μ`. Variance at target `t` is `(a·t² − 2bt + c) / (ac − b²)`. No optimisation loop — one pass.\n\n**Example.**\n\n```python\nimport pandas as pd, numpy as np, matplotlib.pyplot as plt\ndef ret(t): return pd.read_csv(f''/data/quant/{t}.csv'')[''adj_close''].pct_change().dropna().values[-1000:]\nR = np.column_stack([ret(''spy''), ret(''aapl''), ret(''tlt'')])\nmu, S = R.mean(axis=0), np.cov(R, rowvar=False)\nSinv = np.linalg.inv(S); ones = np.ones(3)\na = ones @ Sinv @ ones; b = mu @ Sinv @ ones; c = mu @ Sinv @ mu\ntargets = np.linspace(mu.min(), mu.max(), 50)\nvars_ = (a*targets**2 - 2*b*targets + c) / (a*c - b**2)\nplt.plot(np.sqrt(vars_), targets); plt.xlabel(''vol''); plt.ylabel(''return'')\nprint(round(float(np.sqrt(vars_).min()), 4))\n```\n\n**Your turn.** Replace `___` with the np.cov keyword that treats each column as one variable.\n\n**Expected.** `0.0079`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'portfolio', 'linear-algebra'],
  true,
  32
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000320',
  '00000000-0000-0000-0000-000000000033',
  'quant-33-sharpe-max-drawdown',
  E'Sharpe, max drawdown',
  E'The Sharpe ratio is mean return divided by standard deviation, annualised. Max drawdown is the worst peak-to-trough on the equity curve.',
  E'Compute SPY''s annualised Sharpe ratio and max drawdown.',
  E'**Concept.** Annualised Sharpe = `(r.mean() * 252) / (r.std() * sqrt(252))` for daily data. Max drawdown is `(equity / equity.cummax() - 1).min()`. Both are scalar — print them rounded.\n\n**Example.**\n\n```python\nimport pandas as pd, numpy as np\ndf = pd.read_csv(''/data/quant/spy.csv'')\nr = df[''adj_close''].pct_change().dropna()\nsharpe = (r.mean()*252) / (r.std()*np.sqrt(252))\neq = (1 + r).cumprod()\ndd = (eq / eq.cummax() - 1).min()\nprint(round(sharpe, 2), round(dd, 3))\n```\n\n**Your turn.** Replace `___` with the running-max method.\n\n**Expected.** `0.8 -0.337`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'pandas', 'risk-metrics'],
  true,
  33
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000321',
  '00000000-0000-0000-0000-000000000034',
  'quant-34-sklearn-fit-and-predict',
  E'sklearn fit and predict',
  E'scikit-learn''s API is the same for every estimator: `.fit(X, y)` learns, `.predict(X)` infers, `.score(X, y)` reports R² or accuracy.',
  E'Train a linear regression on a toy dataset and verify the perfect fit.',
  E'**Concept.** Every sklearn estimator inherits `fit/predict/score`. With perfectly linear data, `LinearRegression` recovers the coefficient exactly and `.score` returns 1.0.\n\n**Example.**\n\n```python\nimport numpy as np\nfrom sklearn.linear_model import LinearRegression\nX = np.arange(10).reshape(-1, 1)\ny = 2 * X.ravel() + 3\nmodel = LinearRegression().fit(X, y)\nprint(round(model.score(X, y), 4))\n```\n\n**Your turn.** Replace `___` with the method that trains the model.\n\n**Expected.** `1.0`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'machine-learning', 'regression'],
  true,
  34
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000322',
  '00000000-0000-0000-0000-000000000034',
  'quant-35-lookahead-bias',
  E'Lookahead bias',
  E'In finance ML the order of your rows matters. A random `train_test_split` lets the model see the future — and inflates your Sharpe spectacularly.',
  E'Recognise why a chronological split is the honest baseline.',
  E'**Concept.** `sklearn.model_selection.train_test_split(shuffle=False)` keeps order intact. The first 80% becomes training, last 20% becomes test. Anything else for time series is a bug.\n\n**Example.**\n\n```python\nfrom sklearn.model_selection import train_test_split\nimport numpy as np\nX = np.arange(10).reshape(-1, 1); y = np.arange(10)\n_, X_test, _, _ = train_test_split(X, y, test_size=0.2, shuffle=False)\nprint(X_test.ravel().tolist())\n```\n\n**Predict.** Predict what the test set looks like — last 20% of an ordered range 0..9.\n\n**Expected.** `[8, 9]`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'machine-learning', 'backtesting'],
  true,
  35
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000323',
  '00000000-0000-0000-0000-000000000034',
  'quant-36-momentum-signal-regression',
  E'Momentum signal regression',
  E'A 5-day momentum is a classic feature: did the stock go up over the last week? Regressing next-day return on this is the smallest non-trivial ML model in finance.',
  E'Fit a linear regression of next-day SPY return on lagged 5-day return; report the R².',
  E'**Concept.** `mom_5 = r.shift(1).rolling(5).sum()`. Drop NaNs, split chronologically with shuffle=False, fit `LinearRegression`. R² near zero is *expected* — markets are hard.\n\n**Example.**\n\n```python\nimport pandas as pd, numpy as np\nfrom sklearn.linear_model import LinearRegression\nfrom sklearn.model_selection import train_test_split\nr = pd.read_csv(''/data/quant/spy.csv'')[''adj_close''].pct_change()\ndf = pd.DataFrame({''mom'': r.shift(1).rolling(5).sum(), ''next'': r}).dropna()\nX = df[[''mom'']].values; y = df[''next''].values\nXtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.2, shuffle=False)\nscore = LinearRegression().fit(Xtr, ytr).score(Xte, yte)\nprint(round(score, 4))\n```\n\n**Your turn.** Replace `___` so the split keeps chronological order (no shuffling).\n\n**Expected.** `0.0049`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'machine-learning', 'regression'],
  true,
  36
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000324',
  '00000000-0000-0000-0000-000000000034',
  'quant-37-random-forest-direction-classifier',
  E'Random forest direction classifier',
  E'A forest of decision trees can spot non-linear patterns a linear model would miss — at the cost of being a black box.',
  E'Train a 100-tree random forest to predict next-day direction from 5-day momentum and rolling volatility.',
  E'**Concept.** `RandomForestClassifier(n_estimators=100)` builds 100 trees. Two features: 5-day momentum and 20-day rolling std. The label is `np.sign(next_return)`. Score is accuracy on a chronological test split.\n\n**Example.**\n\n```python\nimport pandas as pd, numpy as np\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import train_test_split\nr = pd.read_csv(''/data/quant/spy.csv'')[''adj_close''].pct_change()\ndf = pd.DataFrame({\n    ''mom'': r.shift(1).rolling(5).sum(),\n    ''vol'': r.shift(1).rolling(20).std(),\n    ''next'': np.sign(r),\n}).dropna()\nX = df[[''mom'',''vol'']].values; y = df[''next''].values\nXtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.2, shuffle=False)\nscore = RandomForestClassifier(n_estimators=100, random_state=0).fit(Xtr, ytr).score(Xte, yte)\nprint(round(score, 3))\n```\n\n**Your turn.** Replace `___` with the method that trains the forest.\n\n**Expected.** `0.526`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'machine-learning'],
  true,
  37
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000325',
  '00000000-0000-0000-0000-000000000034',
  'quant-38-time-series-cross-validation',
  E'Time-series cross-validation',
  E'`TimeSeriesSplit` slices a chronological frame into expanding-window CV folds. Every test fold starts after its train fold — no leakage.',
  E'Run a 5-fold time-series CV on a linear model and average the fold scores.',
  E'**Concept.** `TimeSeriesSplit(n_splits=5)` yields five (train_idx, test_idx) pairs. Loop, fit on train_idx, score on test_idx, average. Use `cross_val_score(...)` for the one-liner.\n\n**Example.**\n\n```python\nimport pandas as pd, numpy as np\nfrom sklearn.linear_model import LinearRegression\nfrom sklearn.model_selection import TimeSeriesSplit, cross_val_score\nr = pd.read_csv(''/data/quant/spy.csv'')[''adj_close''].pct_change()\ndf = pd.DataFrame({''mom'': r.shift(1).rolling(5).sum(), ''next'': r}).dropna()\nX = df[[''mom'']].values; y = df[''next''].values\ntscv = TimeSeriesSplit(n_splits=5)\nscores = cross_val_score(LinearRegression(), X, y, cv=tscv)\nprint(round(scores.mean(), 4))\n```\n\n**Your turn.** Replace `___` with the splitter that respects chronological order.\n\n**Expected.** `0.0`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'machine-learning', 'backtesting'],
  true,
  38
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000326',
  '00000000-0000-0000-0000-000000000034',
  'quant-39-the-p-hacked-sharpe-trap',
  E'The p-hacked Sharpe trap',
  E'Try 1000 random strategies; the best one will look brilliant by chance. Lopez de Prado calls this ''backtest overfitting'' and warns it dwarfs every other risk in quant ML.',
  E'Predict the maximum Sharpe of 1000 pure-noise strategies — and feel why a ''great'' backtest in isolation is meaningless.',
  E'**Concept.** Generate 1000 random return series with mean 0 and σ=0.01. Compute each one''s annualised Sharpe. The MAX across them is several standard deviations above zero — pure chance, not skill.\n\n**Example.**\n\n```python\nimport numpy as np\nrng = np.random.default_rng(42)\nR = rng.normal(0, 0.01, size=(1000, 1000))\nsharpe = R.mean(axis=1) / R.std(axis=1) * np.sqrt(252)\nprint(round(sharpe.max(), 2) > 1.5)\n```\n\n**Predict.** 1000 pure-noise strategies — is the best one''s annualised Sharpe > 1.5?\n\n**Expected.** `True`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'machine-learning', 'backtesting', 'risk-metrics'],
  true,
  39
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000327',
  '00000000-0000-0000-0000-000000000035',
  'quant-40-why-c',
  E'Why C',
  E'Python is where research lives. C is where the inner loop of a matching engine runs a billion times a day. The latency budget is the difference.',
  E'Read a real C limit-order-book node and see it execute.',
  E'**Concept.** The demo below is a small sorted-list LOB written in C, compiled to WASM at `-O3`. Even this tiny example is faster than the equivalent pure-Python: no per-element interpreter overhead, no object headers, just contiguous memory and direct pointer chasing.\n\n**Example.**\n\n```c\n/* Sorted-insert LOB in C — see c-demos/lob_node.c */\ninsert_bid(&book, 1, 100.05, 5);\ninsert_bid(&book, 2, 100.10, 3);\n```\n\n**Your turn.** Click Run demo. The C compiles ahead of time — what you see is `-O3` speed.\n\n**Expected.** `best bid: 100.10`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'c-language', 'low-latency'],
  true,
  40
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000328',
  '00000000-0000-0000-0000-000000000035',
  'quant-41-hello-c',
  E'Hello C',
  E'The simplest C program — `printf` plus `return 0`. Same shape every C program in the world has at its core.',
  E'Print ''hello, C!'' from a C program.',
  E'**Concept.** `#include <stdio.h>` exposes `printf`. `main` must return an `int`. Strings live between double quotes; `\\n` is a newline.\n\n**Example.**\n\n```c\n#include <stdio.h>\nint main() {\n    printf("hello, C!\\n");\n    return 0;\n}\n```\n\n**Your turn.** Replace `___` with the exact string `hello, C!`.\n\n**Expected.** `hello, C!`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'c-language'],
  true,
  41
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000329',
  '00000000-0000-0000-0000-000000000035',
  'quant-42-types-and-arithmetic',
  E'Types and arithmetic',
  E'C has explicit types: `int` is integer, `double` is 8-byte float. Mixing them follows promotion rules — division is the most surprising.',
  E'Print the integer division of 7/2 and the floating-point division of 7.0/2.0.',
  E'**Concept.** `7 / 2` is integer division in C — it gives `3`, not `3.5`. To get the real quotient, one operand must be a float: `7.0 / 2` or `(double)7 / 2`.\n\n**Example.**\n\n```c\n#include <stdio.h>\nint main() {\n    printf("%d %.1f\\n", 7 / 2, 7.0 / 2);\n    return 0;\n}\n```\n\n**Your turn.** Replace `___` with the literal that keeps the second division floating-point.\n\n**Expected.** `3 3.5`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'c-language'],
  true,
  42
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000032a',
  '00000000-0000-0000-0000-000000000035',
  'quant-43-conditionals-and-loops',
  E'Conditionals and loops',
  E'C''s `for` loop has three parts: init, test, increment. Same idea as Python but with explicit types and braces.',
  E'Print the first 5 squares using a for-loop.',
  E'**Concept.** `for (int i = 1; i <= 5; i++) { ... }` runs the body 5 times with i from 1 to 5. `printf("%d ", i*i)` prints each square. After the loop, print a newline.\n\n**Example.**\n\n```c\n#include <stdio.h>\nint main() {\n    for (int i = 1; i <= 5; i++) {\n        printf("%d ", i * i);\n    }\n    printf("\\n");\n    return 0;\n}\n```\n\n**Your turn.** Replace `___` with the increment that advances i by 1 each iteration.\n\n**Expected.** `1 4 9 16 25`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'c-language'],
  true,
  43
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000032b',
  '00000000-0000-0000-0000-000000000035',
  'quant-44-arrays-and-pointers',
  E'Arrays and pointers',
  E'In C, an array''s name decays to a pointer to its first element. Pointer arithmetic walks the array byte-by-byte — `*(p + 2)` is the same as `p[2]`.',
  E'Use pointer arithmetic to print the third element of an array.',
  E'**Concept.** Given `int a[5] = {10,20,30,40,50};` and `int *p = a;`, all of `a[2]`, `p[2]`, `*(p+2)`, `*(a+2)` are `30`. They''re four ways of writing the same thing.\n\n**Example.**\n\n```c\n#include <stdio.h>\nint main() {\n    int a[5] = {10, 20, 30, 40, 50};\n    int *p = a;\n    printf("%d\\n", *(p + 2));\n    return 0;\n}\n```\n\n**Your turn.** Replace `___` with the offset that gives you the third element.\n\n**Expected.** `30`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'c-language', 'memory'],
  true,
  44
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000032c',
  '00000000-0000-0000-0000-000000000035',
  'quant-45-structs',
  E'Structs',
  E'A struct groups related fields. Every market-data tick, every order, every position in a quant system is a struct.',
  E'Define a Bond struct and print its fields.',
  E'**Concept.** `struct Bond { double face; int years; };` declares the shape. `struct Bond b;` declares an instance. Fields are set via `.` (`b.face = 1000.0;`).\n\n**Example.**\n\n```c\n#include <stdio.h>\nstruct Bond {\n    double face;\n    int years;\n};\nint main() {\n    struct Bond b;\n    b.face = 1000.0;\n    b.years = 5;\n    printf("face=%.2f years=%d\\n", b.face, b.years);\n    return 0;\n}\n```\n\n**Your turn.** Replace `___` with the field name we set above.\n\n**Expected.** `face=1000.00 years=5`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'c-language', 'memory'],
  true,
  45
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000032d',
  '00000000-0000-0000-0000-000000000035',
  'quant-46-function-pointers',
  E'Function pointers',
  E'A function pointer lets you pass behaviour, not just data. C''s `qsort` takes one — every C program that sorts a struct uses this pattern.',
  E'Pass a comparison function to `apply` and print the result.',
  E'**Concept.** `int (*f)(int)` is the type ''pointer to a function taking int and returning int''. Pass `square` to `apply(square, 5)` and `apply` calls it as `f(x)`.\n\n**Example.**\n\n```c\n#include <stdio.h>\nint square(int x) { return x * x; }\nint apply(int (*f)(int), int x) { return f(x); }\nint main() {\n    printf("%d\\n", apply(square, 7));\n    return 0;\n}\n```\n\n**Your turn.** Replace `___` with the function name to pass as a function pointer.\n\n**Expected.** `49`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'c-language'],
  true,
  46
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000032e',
  '00000000-0000-0000-0000-000000000035',
  'quant-47-malloc-and-free',
  E'malloc and free',
  E'C makes you allocate and free memory yourself. Forgetting `free` is a leak; freeing twice is a crash. Modern languages hide this; C surfaces it.',
  E'Allocate a 3-int buffer with malloc, write to it, print it, then free it.',
  E'**Concept.** `malloc(3 * sizeof(int))` allocates 12 bytes (on most systems). Cast the result to `int *`. Always `free(p)` when done. The pattern: allocate → use → free.\n\n**Example.**\n\n```c\n#include <stdio.h>\n#include <stdlib.h>\nint main() {\n    int *p = (int *) malloc(3 * sizeof(int));\n    p[0] = 7; p[1] = 8; p[2] = 9;\n    printf("%d %d %d\\n", p[0], p[1], p[2]);\n    free(p);\n    return 0;\n}\n```\n\n**Your turn.** Replace `___` with the function that returns memory to the heap.\n\n**Expected.** `7 8 9`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'c-language', 'memory'],
  true,
  47
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-00000000032f',
  '00000000-0000-0000-0000-000000000035',
  'quant-48-c-ring-buffer',
  E'C ring buffer',
  E'A ring buffer wraps a fixed-size array with head/tail indices. Every HFT feed handler has one. Same pattern: push when not full, pop when not empty.',
  E'Read a fixed-size ring buffer in C and run it to see push/pop in action.',
  E'**Concept.** `head` and `tail` indices wrap modulo CAP. `count` distinguishes empty from full. Real production buffers use atomic ops on the indices for SPSC lock-free use; this demo skips that — same pattern, single-threaded.\n\n**Example.**\n\n```c\n/* See the full source in c-demos/ring_buffer.c */\nrb_push(&rb, 10);   // pushes succeed until count == CAP\nrb_pop(&rb, &out);  // pops out the oldest value (FIFO)\n```\n\n**Your turn.** Click Run demo. Watch what happens when push 5 hits a CAP=4 buffer.\n\n**Expected.** `push(50) FULL`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'c-language', 'low-latency', 'memory'],
  true,
  48
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000330',
  '00000000-0000-0000-0000-000000000035',
  'quant-49-the-same-ring-buffer-in-python',
  E'The same ring buffer in Python',
  E'The Python translation works. It''s also slow. Same algorithm, same memory pattern — what''s missing is the compiled inner loop.',
  E'Implement a fixed-size ring buffer in Python and time it.',
  E'**Concept.** A Python list with manual head/tail indices reproduces the C ring buffer''s logic. Each push or pop is one method call — Python''s per-call overhead is roughly 1µs, so a million ops takes ~1s where C takes ~10ms.\n\n**Example.**\n\n```python\nimport time\nclass RingBuffer:\n    def __init__(self, cap):\n        self.slots = [0]*cap; self.cap = cap; self.head = self.tail = self.count = 0\n    def push(self, x):\n        if self.count == self.cap: return False\n        self.slots[self.head] = x; self.head = (self.head + 1) % self.cap; self.count += 1\n        return True\n    def pop(self):\n        if self.count == 0: return None\n        v = self.slots[self.tail]; self.tail = (self.tail + 1) % self.cap; self.count -= 1\n        return v\nrb = RingBuffer(4)\nfor i in (10, 20, 30, 40, 50): rb.push(i)\nout = []\nwhile (v := rb.pop()) is not None:\n    out.append(v)\nprint(out)\n```\n\n**Your turn.** Replace `___` with the method name that adds items to the buffer.\n\n**Expected.** `[10, 20, 30, 40]`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'performance', 'memory'],
  true,
  49
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000331',
  '00000000-0000-0000-0000-000000000035',
  'quant-50-cython-preview',
  E'Cython preview',
  E'Cython is Python with C type annotations. Add `cdef int` to a hot loop and you''ve trimmed most of the interpreter overhead — same code shape, 50–100× speedup.',
  E'Read a Cython-style snippet and recognise the type annotations.',
  E'**Concept.** A Cython hot loop looks like Python with extra declarations: `cdef int i, n = len(arr)`. The compiler turns the loop body into a C loop with no Python object lookups. Real Cython needs a build step; here we read.\n\n**Example.**\n\n```python\n# This is what a Cython hot-loop sum looks like.\n# In .pyx form, the compiler produces a tight C loop.\ndef cy_sum(arr):\n    # cdef int i, n = len(arr); cdef long total = 0\n    total = 0\n    for i in range(len(arr)):\n        total += arr[i]\n    return total\nprint(cy_sum(list(range(100))))\n```\n\n**Predict.** Predict the sum of 0..99 that the function prints.\n\n**Expected.** `4950`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'performance', 'c-language'],
  true,
  50
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000332',
  '00000000-0000-0000-0000-000000000035',
  'quant-51-cffi-preview',
  E'cffi preview',
  E'cffi lets Python call functions from a `.so` you compiled yourself. The same loop in a C library, called from Python, is what numpy does internally for every ufunc.',
  E'Recognise the cffi binding pattern — declare the function signature, load the shared object, call it.',
  E'**Concept.** cffi''s pattern: `ffi.cdef(''long c_sum(long *arr, int n);'')`, `lib = ffi.dlopen(''libsum.so'')`, then `lib.c_sum(arr, len(arr))`. You''re calling C from Python through a thin shim — the speed is the C code''s, not Python''s.\n\n**Example.**\n\n```python\n# Pseudo-cffi usage — the real call goes to a compiled .so.\n# Here we simulate the same answer with a Python equivalent so\n# you can see the call shape and result.\ndef c_sum_simulated(arr, n):\n    return sum(arr[:n])\nprint(c_sum_simulated(list(range(50)), 50))\n```\n\n**Predict.** Predict the sum of 0..49 the (simulated) C call returns.\n\n**Expected.** `1225`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'performance', 'c-language'],
  true,
  51
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.skills (slug, name) values
  ('backtesting', 'Backtesting'),
  ('black-scholes', 'Black-Scholes'),
  ('c-language', 'C language'),
  ('greeks', 'Greeks'),
  ('linear-algebra', 'Linear algebra'),
  ('low-latency', 'Low latency'),
  ('machine-learning', 'Machine learning'),
  ('matplotlib', 'Matplotlib'),
  ('memory', 'Memory & layout'),
  ('monte-carlo', 'Monte Carlo'),
  ('numpy', 'NumPy'),
  ('options', 'Options'),
  ('pandas', 'pandas'),
  ('performance', 'Performance engineering'),
  ('portfolio', 'Portfolio theory'),
  ('quant', 'Quantitative finance'),
  ('random-numbers', 'Random number generation'),
  ('regression', 'Regression'),
  ('risk-metrics', 'Risk metrics'),
  ('statistics', 'Statistics'),
  ('time-series', 'Time series'),
  ('vectorisation', 'Vectorisation')
on conflict (slug) do update set name = excluded.name;
