-- AUTO-GENERATED by scripts/generate_quant.py
-- Quant track challenge inserts. Track + modules live in
-- supabase/quant_programmer_seed.sql — apply that first.

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000300',
  '00000000-0000-0000-0000-000000000031',
  'quant-01-why-numpy',
  E'Why numpy',
  E'Python''s for-loops feel friendly until you sum a million numbers. numpy''s array operations push the work down into C — same answer, ~50× faster.',
  E'See the speed gap between pure Python and numpy on a simple sum.',
  E'**Concept.** numpy arrays look like Python lists but store data contiguously in memory and operate on it in compiled code. The same logical work runs an order of magnitude faster — without any loop appearing in your Python.\n\n**Example.**\n\n```python\nimport numpy as np, time\nn = 1_000_000\nxs = list(range(n))\narr = np.arange(n)\nprint(sum(xs) == int(arr.sum()))\n```\n\n**Predict.** Both compute the same sum 0+1+…+999999. Predict the printed result.\n\n**Expected.** `True`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'vectorisation'],
  true,
  1
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000301',
  '00000000-0000-0000-0000-000000000031',
  'quant-02-creating-arrays',
  E'Creating arrays',
  E'Three constructors handle 95% of real array creation: a literal list, all-zeros of a given shape, and an evenly-spaced range.',
  E'Use np.array, np.zeros, and np.linspace to build arrays from different starting points.',
  E'**Concept.** `np.array([…])` lifts a Python list. `np.zeros(n)` allocates `n` zeros. `np.linspace(start, stop, n)` returns `n` evenly spaced points including both endpoints — the canonical x-axis builder.\n\n**Example.**\n\n```python\nimport numpy as np\na = np.array([1.0, 2.0, 3.0])\nb = np.zeros(3)\nc = np.linspace(0, 1, 5)\nprint(a, b, c, sep='' | '')\n```\n\n**Your turn.** Fill the blanks so the output shows the literal, three zeros, and five evenly-spaced points from 0 to 1.\n\n**Expected.** `[1. 2. 3.] | [0. 0. 0.] | [0.   0.25 0.5  0.75 1.  ]`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy'],
  true,
  2
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000302',
  '00000000-0000-0000-0000-000000000031',
  'quant-03-broadcasting',
  E'Broadcasting',
  E'When you add a 1-D array to a 2-D array, numpy stretches the smaller one along the missing axis. It saves you from writing nested loops.',
  E'Read a broadcast expression and predict the resulting shape and values.',
  E'**Concept.** If a `(3,)` array meets a `(4, 3)` array, numpy treats the row as if repeated four times. The shapes must align from the trailing axis — `(3,)` vs `(4, 3)` works; `(4,)` vs `(4, 3)` doesn''t.\n\n**Example.**\n\n```python\nimport numpy as np\nM = np.zeros((4, 3))\nrow = np.array([10, 20, 30])\nprint(M + row)\n```\n\n**Predict.** The first row of `M + row` is printed. What does it look like?\n\n**Expected.** `[10. 20. 30.]`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'vectorisation'],
  true,
  3
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000303',
  '00000000-0000-0000-0000-000000000031',
  'quant-04-boolean-masks',
  E'Boolean masks',
  E'A boolean mask is an array of True/False the same shape as your data. Indexing with it keeps the True entries — a vectorised filter.',
  E'Keep only the positive entries of an array using a boolean mask.',
  E'**Concept.** `arr > 0` returns a boolean array of the same shape. Using it as an index (`arr[mask]`) returns just the elements where the mask is True. No loops, no list comprehension — pure vectorised filtering.\n\n**Example.**\n\n```python\nimport numpy as np\nr = np.array([-0.02, 0.01, -0.005, 0.015, 0.0, 0.03])\npositive = r[r > 0]\nprint(positive)\n```\n\n**Your turn.** Replace `___` with the operator that keeps strictly positive returns only.\n\n**Expected.** `[0.01  0.015 0.03 ]`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'vectorisation'],
  true,
  4
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000304',
  '00000000-0000-0000-0000-000000000031',
  'quant-05-covariance-via-matrix-algebra',
  E'Covariance via matrix algebra',
  E'Covariance between asset returns underpins portfolio theory. The textbook formula `(X - μ).T @ (X - μ) / n` is one line of numpy.',
  E'Compute a 2x2 covariance matrix from two return series using matrix multiplication.',
  E'**Concept.** Stack two demeaned return series as columns of `X` (shape `(n, 2)`). Then `X.T @ X / n` is the 2x2 covariance matrix. The diagonal is each series'' variance; off-diagonal is their covariance.\n\n**Example.**\n\n```python\nimport numpy as np\nrng = np.random.default_rng(0)\nX = rng.normal(size=(1000, 2))\nXd = X - X.mean(axis=0)\ncov = Xd.T @ Xd / X.shape[0]\nprint(np.round(cov, 2))\n```\n\n**Your turn.** Replace `___` with the attribute that transposes the matrix.\n\n**Expected.** `[[ 1.04 -0.02] ·  [-0.02  0.96]]`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'linear-algebra', 'statistics'],
  true,
  5
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000305',
  '00000000-0000-0000-0000-000000000031',
  'quant-06-reproducible-random-numbers',
  E'Reproducible random numbers',
  E'Every backtest you write touches a random number generator. Seeding it makes your work reproducible — same input, same answer.',
  E'Generate two arrays of standard-normal draws and confirm the seed makes them identical.',
  E'**Concept.** `np.random.default_rng(seed)` returns a Generator. Same seed in, same draws out — every time. The legacy `np.random.seed` global is fine for scripts; default_rng is the modern, thread-safe API.\n\n**Example.**\n\n```python\nimport numpy as np\na = np.random.default_rng(42).normal(size=3)\nb = np.random.default_rng(42).normal(size=3)\nprint(np.array_equal(a, b))\n```\n\n**Your turn.** Replace `___` so both generators draw the same sequence.\n\n**Expected.** `True`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'random-numbers'],
  true,
  6
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000306',
  '00000000-0000-0000-0000-000000000031',
  'quant-07-statistical-reductions',
  E'Statistical reductions',
  E'Mean, standard deviation, and percentiles let you summarise a return distribution in one line each — they''re the vocabulary of every research note.',
  E'Compute the mean, standard deviation, and 95th percentile of a sample.',
  E'**Concept.** numpy reductions take an axis (or none, for the whole array). `arr.mean()` and `arr.std()` are methods; `np.percentile(arr, q)` is a function — `q` is in 0–100, not 0–1.\n\n**Example.**\n\n```python\nimport numpy as np\nrng = np.random.default_rng(0)\nr = rng.normal(loc=0.001, scale=0.02, size=10_000)\nprint(round(r.mean(), 4), round(r.std(), 4), round(np.percentile(r, 95), 4))\n```\n\n**Your turn.** Fill the three blanks with the reduction names.\n\n**Expected.** `0.0011 0.02 0.0338`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'statistics'],
  true,
  7
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000307',
  '00000000-0000-0000-0000-000000000031',
  'quant-08-why-numpy-is-fast',
  E'Why numpy is fast',
  E'numpy''s headline numbers don''t come from magic — they come from C. Real quant libraries like HFT-Orderbook ship pure-Python LOBs that show exactly what ''slow'' looks like.',
  E'Recognise that numpy is fast because the inner loop is compiled C, not Python.',
  E'**Concept.** numpy stores arrays as contiguous C buffers and runs ufuncs as tight C loops with no Python overhead per element. The same loop in pure Python pays interpreter overhead per iteration — typically 50–100× slower.\n\n**Example.**\n\n```python\nimport numpy as np\nx = np.arange(1_000_000)\n# Both compute (1+2+...+999999) but only one is a Python loop.\nprint(int(x.sum()))\n```\n\n**Predict.** Predict the printed sum of 0..999999.\n\n**Expected.** `499999500000`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'performance'],
  true,
  8
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000308',
  '00000000-0000-0000-0000-000000000031',
  'quant-09-vectorising-a-rolling-mean',
  E'Vectorising a rolling mean',
  E'A 30-day rolling mean of returns is one of the most common features in quant work. The naive loop is O(n*window); numpy''s cumulative-sum trick makes it O(n).',
  E'Replace a Python for-loop with `np.cumsum` to compute a rolling mean.',
  E'**Concept.** If `c = np.cumsum(x)`, then the window-`w` sum ending at index `i` is `c[i] - c[i-w]`. Divide by `w` for the mean. One pass, no inner loop.\n\n**Example.**\n\n```python\nimport numpy as np\nx = np.array([1, 2, 3, 4, 5, 6], dtype=float)\nw = 3\nc = np.concatenate(([0], np.cumsum(x)))\nroll = (c[w:] - c[:-w]) / w\nprint(roll)\n```\n\n**Your turn.** Fill in the cumulative-sum function name.\n\n**Expected.** `[2. 3. 4. 5.]`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'vectorisation', 'performance'],
  true,
  9
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.challenges (
  id, module_id, slug, title, scenario, learner_goal, instructions,
  repo_template_url, repo_branch, validation_config_json, ai_rules_json,
  skills, is_free, order_index
) values (
  '00000000-0000-0000-0000-000000000309',
  '00000000-0000-0000-0000-000000000031',
  'quant-10-plot-a-price-path',
  E'Plot a price path',
  E'Every quant chart starts with `plt.plot`. Get the first one right — labeled axes, a title — and the rest follow.',
  E'Plot a simulated geometric Brownian motion price path with labelled axes.',
  E'**Concept.** `plt.plot(x, y)` draws a line. `plt.xlabel`, `plt.ylabel`, `plt.title` annotate the chart. matplotlib''s pyplot API mirrors MATLAB — one statement per directive.\n\n**Example.**\n\n```python\nimport numpy as np, matplotlib.pyplot as plt\nrng = np.random.default_rng(0)\nshocks = rng.normal(0, 0.01, 252)\nprice = 100 * np.exp(np.cumsum(shocks))\nplt.plot(price)\nplt.title(''Simulated price path''); plt.xlabel(''day''); plt.ylabel(''price'')\nprint(''plotted'')\n```\n\n**Your turn.** Replace `___` with the variable holding the price series.\n\n**Expected.** `plotted`',
  null,
  null,
  '{}',
  '{"max_hint_level": 2, "do_not_reveal_solution": false, "encourage_tests_first": false}',
  array['quant', 'numpy', 'matplotlib', 'monte-carlo'],
  true,
  10
)
on conflict (slug) do update set
  module_id = excluded.module_id,
  title = excluded.title,
  scenario = excluded.scenario,
  learner_goal = excluded.learner_goal,
  instructions = excluded.instructions,
  repo_template_url = excluded.repo_template_url,
  repo_branch = excluded.repo_branch,
  validation_config_json = excluded.validation_config_json,
  ai_rules_json = excluded.ai_rules_json,
  skills = excluded.skills,
  is_free = excluded.is_free,
  order_index = excluded.order_index;

insert into public.skills (slug, name) values
  ('linear-algebra', 'Linear algebra'),
  ('matplotlib', 'Matplotlib'),
  ('monte-carlo', 'Monte Carlo'),
  ('numpy', 'NumPy'),
  ('performance', 'Performance engineering'),
  ('quant', 'Quantitative finance'),
  ('random-numbers', 'Random number generation'),
  ('statistics', 'Statistics'),
  ('vectorisation', 'Vectorisation')
on conflict (slug) do update set name = excluded.name;
