"use client";

import { Button } from "@/components/ui/button";

type Props = {
  open: boolean;
  pending: boolean;
  onCancel: () => void;
  onConfirm: () => void;
};

export function ShowAnswerModal({ open, pending, onCancel, onConfirm }: Props) {
  if (!open) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
      <div className="w-full max-w-md rounded-lg border border-border bg-white p-6 shadow-xl">
        <h3 className="mb-2 text-lg font-semibold">Show me the answer?</h3>
        <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
          This replaces the code you&apos;ve written with a working version generated by the AI.
          You&apos;ll be able to read the fix in the editor and run the tests against it. Your
          previous edits will be lost unless you&apos;ve saved them elsewhere.
        </p>
        <p className="mb-4 text-xs text-muted-foreground">
          Use this when you&apos;ve genuinely tried for a while — reading a working solution is a
          good way to learn, but it&apos;s most useful after you&apos;ve struggled with the
          problem yourself.
        </p>
        <div className="flex items-center justify-end gap-2">
          <Button variant="outline" size="sm" onClick={onCancel} disabled={pending}>
            Cancel
          </Button>
          <Button size="sm" onClick={onConfirm} disabled={pending}>
            {pending ? "Generating…" : "Replace my code"}
          </Button>
        </div>
      </div>
    </div>
  );
}
