// AUTO-GENERATED by scripts/generate_mental_models.py
// Per-concept runtime config: Play widget JSON, MCQs,
// rubric structure. Read by the concept page.

export type ConceptConfig = {
  slug: string;
  playWidgetKind: string;
  playWidget: Record<string, unknown>;
  checkMcqs: Array<{
    q: string;
    options: string[];
    correct: number;
    why?: string;
  }>;
  reflectQuestion: string;
  reflectRubric: Record<string, unknown>;
  recallChecks: Array<Record<string, unknown>>;
};

export const MENTAL_MODELS_CONFIG: Record<string, ConceptConfig> = {
  'variables-names': {
    slug: 'variables-names',
    playWidgetKind: 'code-stepper',
    playWidget: {"title": "Step through a name-binding scenario", "code": "a = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)", "steps": [{"line": 1, "bindings": {"a": "→ list#1 [1, 2, 3]"}, "heap": [{"id": "list#1", "value": "[1, 2, 3]"}], "caption": "`a` is bound to a list — one arrow from `a` to list#1."}, {"line": 2, "bindings": {"a": "→ list#1", "b": "→ list#1"}, "heap": [{"id": "list#1", "value": "[1, 2, 3]"}], "caption": "`b = a` does NOT copy — it draws a second arrow to the same list#1."}, {"line": 3, "bindings": {"a": "→ list#1", "b": "→ list#1"}, "heap": [{"id": "list#1", "value": "[1, 2, 3, 4]"}], "caption": "`b.append(4)` mutates list#1 itself — both `a` and `b` see the change."}, {"line": 4, "bindings": {"a": "→ list#1", "b": "→ list#1"}, "heap": [{"id": "list#1", "value": "[1, 2, 3, 4]"}], "caption": "`print(a)` reads the (now-mutated) list. Output: [1, 2, 3, 4]."}]},
    checkMcqs: [{"q": "Given `xs = {'k': 1}` and `ys = xs`, what does `ys['k'] = 9; print(xs)` print?", "options": ["{'k': 1}", "{'k': 9}", "TypeError", "None"], "correct": 1, "why": "`ys = xs` binds `ys` to the *same* dict. Mutating via either name is visible through the other."}, {"q": "Given `s = 'hi'; t = s; t = t + '!'`, what does `print(s)` print?", "options": ["'hi'", "'hi!'", "'!hi'", "Error"], "correct": 0, "why": "Strings are immutable. `t = t + '!'` rebinds `t` to a new string; `s` still points at the original 'hi'."}],
    reflectQuestion: 'In two sentences, explain to a colleague what a *variable* is in Python — and why `b = a` followed by `b.append(4)` changes `a` too.',
    reflectRubric: {"must_mention": ["name", "value", "scope"], "must_distinguish": [["binding", "copying"], ["mutable", "immutable"]], "must_explain": ["two names can be bound to the same object", "mutating the object affects every name bound to it"]},
    recallChecks: [{"kind": "mcq", "q": "Given `xs = [1]; ys = xs; ys.append(2)`, what is `xs`?", "options": ["[1]", "[1, 2]", "TypeError"], "correct": 1}, {"kind": "mcq", "q": "If `s = 'a'; t = s; t = 'b'`, what is `s`?", "options": ["'a'", "'b'", "None"], "correct": 0}, {"kind": "mcq", "q": "What does `b = a` do when `a` is a list?", "options": ["Copies the list", "Creates a second name for the same list", "Raises an exception"], "correct": 1}],
  },
  'references-values': {
    slug: 'references-values',
    playWidgetKind: 'memory-model-viewer',
    playWidget: {"title": "The shared default list", "frames": [{"caption": "At function definition: Python builds the default list once.", "stack": [{"name": "(module)", "vars": {}}], "heap": [{"id": "list#1", "value": "[]", "labels": ["add_one.__defaults__[0]"]}]}, {"caption": "Call 1: xs binds to list#1 → append(1) mutates it.", "stack": [{"name": "(module)", "vars": {}}, {"name": "add_one", "vars": {"xs": "→ list#1"}}], "heap": [{"id": "list#1", "value": "[1]", "labels": ["add_one.__defaults__[0]", "xs"]}]}, {"caption": "Call 2: xs binds to the SAME list#1 → another mutation.", "stack": [{"name": "(module)", "vars": {}}, {"name": "add_one", "vars": {"xs": "→ list#1"}}], "heap": [{"id": "list#1", "value": "[1, 1]", "labels": ["add_one.__defaults__[0]", "xs"]}]}]},
    checkMcqs: [{"q": "What does this print?\n\n```\ndef f(d={}):\n    d['n'] = d.get('n', 0) + 1\n    return d\n\nprint(f()); print(f())\n```", "options": ["{'n': 1} {'n': 1}", "{'n': 1} {'n': 2}", "{'n': 0} {'n': 1}", "TypeError"], "correct": 1, "why": "Same trap as lists. The dict default is built once and reused across calls."}, {"q": "Which is the safe default for a list-typed argument in Python?", "options": ["`def f(xs=[]):`", "`def f(xs=list()):`", "`def f(xs=None):` and create the list inside", "`def f(xs):` and document that the caller must pass one"], "correct": 2, "why": "The None-sentinel pattern is the canonical fix — a fresh list per call, no shared state."}],
    reflectQuestion: 'In two sentences, explain why mutating a default argument value in Python can leak state across calls — and how to fix it.',
    reflectRubric: {"must_mention": ["default", "mutable", "shared"], "must_distinguish": [["evaluation at definition", "evaluation per call"]], "must_explain": ["the default object is created once", "every call without the argument reuses that same object", "use None as the sentinel and create a fresh object inside"]},
    recallChecks: [{"kind": "mcq", "q": "Calling `f()` twice when `f` has `xs=[]` as default and appends 1 produces what after the second call?", "options": ["[1]", "[1, 1]", "[]"], "correct": 1}, {"kind": "mcq", "q": "The Pythonic safe-default pattern is:", "options": ["`xs=[]`", "`xs=None` + check inside", "`xs=list()`"], "correct": 1}, {"kind": "mcq", "q": "Default arguments in Python are evaluated…", "options": ["once, at definition", "every call", "lazily, on first use"], "correct": 0}],
  },
  'control-flow': {
    slug: 'control-flow',
    playWidgetKind: 'code-stepper',
    playWidget: {"title": "Step through a continue-in-a-loop", "code": "total = 0\nfor i in range(6):\n    if i % 2 != 0:\n        continue\n    total += i\nprint(total)", "steps": [{"line": 1, "bindings": {"total": "0"}, "caption": "`total` starts at 0."}, {"line": 2, "bindings": {"total": "0", "i": "0"}, "caption": "First iteration: i=0 (even)."}, {"line": 5, "bindings": {"total": "0", "i": "0"}, "caption": "0 % 2 == 0, so we skip continue and reach the add."}, {"line": 5, "bindings": {"total": "0", "i": "1"}, "caption": "Second iteration: i=1 (odd). Condition triggers."}, {"line": 4, "bindings": {"total": "0", "i": "1"}, "caption": "`continue` — jump straight back to the loop header. `total` unchanged."}, {"line": 5, "bindings": {"total": "2", "i": "2"}, "caption": "i=2 (even). 0 + 2 = 2."}, {"line": 5, "bindings": {"total": "2", "i": "3"}, "caption": "i=3 (odd). continue again. No change."}, {"line": 5, "bindings": {"total": "6", "i": "4"}, "caption": "i=4 (even). 2 + 4 = 6."}, {"line": 5, "bindings": {"total": "6", "i": "5"}, "caption": "i=5 (odd). continue. Final total 6."}, {"line": 6, "bindings": {"total": "6"}, "caption": "Print 6 — the sum of even numbers 0..4."}]},
    checkMcqs: [{"q": "How many times does the body of `for i in range(4): if i == 2: break; print(i)` actually print?", "options": ["1", "2", "3", "4"], "correct": 1, "why": "`break` exits the loop entirely at i=2 — only i=0 and i=1 reach the print, so 2 lines."}, {"q": "What does `continue` do inside a `for` loop?", "options": ["Exits the loop entirely", "Skips the rest of the current iteration and starts the next", "Restarts the loop from the beginning", "Pauses execution"], "correct": 1, "why": "`continue` is a per-iteration shortcut, not a per-loop shortcut. The loop header runs again immediately."}],
    reflectQuestion: 'In two sentences, describe how `break` and `continue` differ — and why someone reading code at a glance might confuse them.',
    reflectRubric: {"must_mention": ["break", "continue", "loop"], "must_distinguish": [["exit the loop", "skip the iteration"]], "must_explain": ["break exits the enclosing loop entirely", "continue jumps to the next iteration of the same loop", "both are early-exit shortcuts inside the loop body"]},
    recallChecks: [{"kind": "mcq", "q": "`break` inside a `for` loop:", "options": ["skips one iteration", "exits the loop", "restarts the loop"], "correct": 1}, {"kind": "mcq", "q": "`continue` inside a `for` loop:", "options": ["skips to next iteration", "exits the loop", "raises an exception"], "correct": 0}, {"kind": "mcq", "q": "If an `if` condition is False, the matching block:", "options": ["runs", "is skipped", "raises TypeError"], "correct": 1}],
  },
  'recursion': {
    slug: 'recursion',
    playWidgetKind: 'call-stack-visualiser',
    playWidget: {"title": "Watch the call stack of fact(4)", "function_name": "fact", "frames": [{"caption": "Initial call.", "stack": ["fact(4)"]}, {"caption": "fact(4) calls fact(3).", "stack": ["fact(4)", "fact(3)"]}, {"caption": "fact(3) calls fact(2).", "stack": ["fact(4)", "fact(3)", "fact(2)"]}, {"caption": "fact(2) calls fact(1).", "stack": ["fact(4)", "fact(3)", "fact(2)", "fact(1)"]}, {"caption": "fact(1) hits the base case and returns 1. The frame pops.", "stack": ["fact(4)", "fact(3)", "fact(2) ← 1"]}, {"caption": "fact(2) computes 2 * 1 = 2 and returns. Pop.", "stack": ["fact(4)", "fact(3) ← 2"]}, {"caption": "fact(3) computes 3 * 2 = 6 and returns. Pop.", "stack": ["fact(4) ← 6"]}, {"caption": "fact(4) computes 4 * 6 = 24 and returns. Stack empty.", "stack": []}]},
    checkMcqs: [{"q": "What's missing from this recursive function?\n\n```\ndef count_down(n):\n    print(n)\n    count_down(n - 1)\n```", "options": ["Nothing — it works", "A base case", "A return statement", "A loop"], "correct": 1, "why": "No base case → infinite recursion → RecursionError. Add `if n <= 0: return` at the top."}, {"q": "How many stack frames are live (not yet returned) at the moment `fact(1)` is about to compute its return value, when called as `fact(5)`?", "options": ["1", "3", "5", "Infinite"], "correct": 2, "why": "fact(5), fact(4), fact(3), fact(2), fact(1) — five frames all live until the base case starts unwinding."}],
    reflectQuestion: 'In two sentences, explain why a recursive function needs a base case — and what happens at runtime if you forget it.',
    reflectRubric: {"must_mention": ["base case", "stack", "recursive"], "must_distinguish": [["recursive case", "base case"]], "must_explain": ["the base case is the input the function can answer without recursing", "without it the stack grows until RecursionError", "each call adds a frame; the base case starts the unwinding"]},
    recallChecks: [{"kind": "mcq", "q": "A recursive function with no base case will:", "options": ["return None", "raise RecursionError", "loop forever"], "correct": 1}, {"kind": "mcq", "q": "Each recursive call adds:", "options": ["a CPU register", "a stack frame", "a global variable"], "correct": 1}, {"kind": "mcq", "q": "fact(3) calls how many functions before the first return?", "options": ["1", "3", "9"], "correct": 1}],
  },
};
