// AUTO-GENERATED by scripts/generate_mental_models.py
// Per-concept runtime config: Play widget JSON, MCQs,
// rubric structure. Read by the concept page.

export type ConceptConfig = {
  slug: string;
  playWidgetKind: string;
  playWidget: Record<string, unknown>;
  checkMcqs: Array<{
    q: string;
    options: string[];
    correct: number;
    why?: string;
  }>;
  reflectQuestion: string;
  reflectRubric: Record<string, unknown>;
  recallChecks: Array<Record<string, unknown>>;
};

export const MENTAL_MODELS_CONFIG: Record<string, ConceptConfig> = {
  'variables-names': {
    slug: 'variables-names',
    playWidgetKind: 'code-stepper',
    playWidget: {"title": "Step through a name-binding scenario", "code": "a = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)", "steps": [{"line": 1, "bindings": {"a": "→ list#1 [1, 2, 3]"}, "heap": [{"id": "list#1", "value": "[1, 2, 3]"}], "caption": "`a` is bound to a list — one arrow from `a` to list#1."}, {"line": 2, "bindings": {"a": "→ list#1", "b": "→ list#1"}, "heap": [{"id": "list#1", "value": "[1, 2, 3]"}], "caption": "`b = a` does NOT copy — it draws a second arrow to the same list#1."}, {"line": 3, "bindings": {"a": "→ list#1", "b": "→ list#1"}, "heap": [{"id": "list#1", "value": "[1, 2, 3, 4]"}], "caption": "`b.append(4)` mutates list#1 itself — both `a` and `b` see the change."}, {"line": 4, "bindings": {"a": "→ list#1", "b": "→ list#1"}, "heap": [{"id": "list#1", "value": "[1, 2, 3, 4]"}], "caption": "`print(a)` reads the (now-mutated) list. Output: [1, 2, 3, 4]."}]},
    checkMcqs: [{"q": "Given `xs = {'k': 1}` and `ys = xs`, what does `ys['k'] = 9; print(xs)` print?", "options": ["{'k': 1}", "{'k': 9}", "TypeError", "None"], "correct": 1, "why": "`ys = xs` binds `ys` to the *same* dict. Mutating via either name is visible through the other."}, {"q": "Given `s = 'hi'; t = s; t = t + '!'`, what does `print(s)` print?", "options": ["'hi'", "'hi!'", "'!hi'", "Error"], "correct": 0, "why": "Strings are immutable. `t = t + '!'` rebinds `t` to a new string; `s` still points at the original 'hi'."}],
    reflectQuestion: 'In two sentences, explain to a colleague what a *variable* is in Python — and why `b = a` followed by `b.append(4)` changes `a` too.',
    reflectRubric: {"must_mention": ["name", "value", "scope"], "must_distinguish": [["binding", "copying"], ["mutable", "immutable"]], "must_explain": ["two names can be bound to the same object", "mutating the object affects every name bound to it"]},
    recallChecks: [{"kind": "mcq", "q": "Given `xs = [1]; ys = xs; ys.append(2)`, what is `xs`?", "options": ["[1]", "[1, 2]", "TypeError"], "correct": 1}, {"kind": "mcq", "q": "If `s = 'a'; t = s; t = 'b'`, what is `s`?", "options": ["'a'", "'b'", "None"], "correct": 0}, {"kind": "mcq", "q": "What does `b = a` do when `a` is a list?", "options": ["Copies the list", "Creates a second name for the same list", "Raises an exception"], "correct": 1}],
  },
};
