// AUTO-GENERATED by scripts/generate_python_basics.py
// Inline runner config for the 25 Python Basics lessons.

import type { ChallengeRunnerConfig } from "@/lib/featured-files";

export const PYTHON_BASICS_CONFIG: Record<string, ChallengeRunnerConfig> = {
  "python-basics-01-hello-python": {
  "mode": "fillblank",
  "template": "___(\"hello, Python!\")",
  "expected_stdout": "hello, Python!",
  "hint": "The function that shows text on screen."
},
  "python-basics-02-variables": {
  "mode": "fillblank",
  "template": "___ = \"Python\"\nprint(language)",
  "expected_stdout": "Python",
  "hint": "The variable name on the left of `=` should match the name used in `print()`."
},
  "python-basics-03-strings-and-f-strings": {
  "mode": "fillblank",
  "template": "language = \"Python\"\nprint(f\"My favourite language is {___}\")",
  "expected_stdout": "My favourite language is Python",
  "hint": "What variable name did the line above define?"
},
  "python-basics-04-numbers-and-arithmetic": {
  "mode": "predict",
  "code": "print(10 + 3 * 2)",
  "expected_stdout": "16",
  "prompt": "What integer does this print?"
},
  "python-basics-05-type-conversion": {
  "mode": "fillblank",
  "template": "age_string = \"42\"\nage_in_eight_years = ___(age_string) + 8\nprint(age_in_eight_years)",
  "expected_stdout": "50",
  "hint": "The function that turns a string of digits into an integer."
},
  "python-basics-06-booleans-and-comparisons": {
  "mode": "predict",
  "code": "print(7 != 8)",
  "expected_stdout": "True",
  "prompt": "Is `7 != 8` True or False?"
},
  "python-basics-07-if-elif-else": {
  "mode": "fillblank",
  "template": "temperature = 5\nif temperature ___ 10:\n    print(\"cold\")\nelse:\n    print(\"warm\")",
  "expected_stdout": "cold",
  "hint": "Pick the comparison operator that makes `5 _ 10` true."
},
  "python-basics-08-logical-operators": {
  "mode": "predict",
  "code": "print(10 > 5 or 10 > 100)",
  "expected_stdout": "True",
  "prompt": "Is at least one side True?"
},
  "python-basics-09-for-loops-with-range": {
  "mode": "fillblank",
  "template": "for i in range(1, ___):\n    print(i)",
  "expected_stdout": "1\n2\n3\n4\n5",
  "hint": "`range(start, stop)` stops BEFORE `stop`, so what number do you put to include 5?"
},
  "python-basics-10-for-loops-over-lists": {
  "mode": "fillblank",
  "template": "names = [\"Ada\", \"Linus\", \"Grace\"]\nfor ___ in names:\n    print(name)",
  "expected_stdout": "Ada\nLinus\nGrace",
  "hint": "The variable name in the `for` line should match the name used inside the loop."
},
  "python-basics-11-while-loops": {
  "mode": "fillblank",
  "template": "count = 5\nwhile count > 0:\n    print(count)\n    count = count ___ 1\nprint(\"Go!\")",
  "expected_stdout": "5\n4\n3\n2\n1\nGo!",
  "hint": "Each iteration needs to make `count` smaller \u2014 which operator?"
},
  "python-basics-12-break-and-continue": {
  "mode": "predict",
  "code": "for i in range(5):\n    if i == 3:\n        break\n    print(i * 2)",
  "expected_stdout": "0\n2\n4",
  "prompt": "The loop breaks when `i == 3`. What does it print before that?"
},
  "python-basics-13-lists": {
  "mode": "fillblank",
  "template": "scores = [95, 88, 76, 60]\nprint(scores[___])",
  "expected_stdout": "88",
  "hint": "The first element is at index 0, so the SECOND is at\u2026?"
},
  "python-basics-14-list-operations": {
  "mode": "fillblank",
  "template": "fruits = [\"apple\", \"banana\"]\nfruits.___(\"strawberry\")\nprint(len(fruits))",
  "expected_stdout": "3",
  "hint": "The list method that adds an item to the end."
},
  "python-basics-15-dictionaries": {
  "mode": "fillblank",
  "template": "country = {\"name\": \"France\", \"capital\": \"Paris\", \"population\": 67}\nprint(country[___])",
  "expected_stdout": "Paris",
  "hint": "Use the key (as a string) inside square brackets."
},
  "python-basics-16-sets-and-tuples": {
  "mode": "predict",
  "code": "print(len({1, 2, 2, 2, 3}))",
  "expected_stdout": "3",
  "prompt": "Sets remove duplicates. How many unique values are there?"
},
  "python-basics-17-defining-functions": {
  "mode": "fillblank",
  "template": "def ___():\n    print(\"Python rocks\")\n\nsay_python()\nsay_python()",
  "expected_stdout": "Python rocks\nPython rocks",
  "hint": "The function name in `def NAME():` should match the call below."
},
  "python-basics-18-parameters": {
  "mode": "fillblank",
  "template": "def welcome(___):\n    print(f\"Welcome, {name}\")\n\nwelcome(\"Grace\")",
  "expected_stdout": "Welcome, Grace",
  "hint": "The parameter name in the parentheses should match the variable used inside the body."
},
  "python-basics-19-return-values": {
  "mode": "fillblank",
  "template": "def add(a, b):\n    return ___\n\nprint(add(2, 3))\nprint(add(10, 20))",
  "expected_stdout": "5\n30",
  "hint": "The expression that adds two numbers \u2014 using the parameter names `a` and `b`."
},
  "python-basics-20-local-vs-global-scope": {
  "mode": "predict",
  "code": "count = 5\ndef add_one():\n    count = 100\n    print(count)\n\nadd_one()\nprint(count)",
  "expected_stdout": "100\n5",
  "prompt": "What does each `print` output, in order, separated by a newline?"
},
  "python-basics-21-try-and-except": {
  "mode": "fillblank",
  "template": "user = {\"name\": \"Ada\"}\ntry:\n    email = user[\"email\"]\n___ KeyError:\n    email = \"unknown\"\nprint(email)",
  "expected_stdout": "unknown",
  "hint": "The keyword that starts a fallback block when a `try` raises an error."
},
  "python-basics-22-list-comprehensions": {
  "mode": "fillblank",
  "template": "squares = [n ___ 2 for n in range(1, 6)]\nprint(squares)",
  "expected_stdout": "[1, 4, 9, 16, 25]",
  "hint": "The power operator in Python is two characters."
},
  "python-basics-23-imports-and-the-standard-library": {
  "mode": "fillblank",
  "template": "___ math\nprint(round(math.pi, 2))",
  "expected_stdout": "3.14",
  "hint": "The keyword that pulls a module into your file."
},
  "python-basics-24-defining-classes": {
  "mode": "fillblank",
  "template": "class Greeter:\n    def __init__(self, name):\n        self.___ = name\n\n    def greet(self):\n        print(f\"Hello from {self.name}\")\n\ng = Greeter(\"Python\")\ng.greet()",
  "expected_stdout": "Hello from Python",
  "hint": "The attribute name on `self` should match what `greet()` reads as `self.name`."
},
  "python-basics-25-a-tiny-to-do-list": {
  "mode": "fillblank",
  "template": "tasks = []\n\ndef add_task(title, done=False):\n    tasks.___({\"title\": title, \"done\": done})\n\ndef show_tasks():\n    for task in tasks:\n        mark = \"x\" if task[\"done\"] else \" \"\n        print(f\"- [{mark}] {task['title']}\")\n\nadd_task(\"Learn Python\")\nadd_task(\"Drink coffee\", done=True)\nadd_task(\"Write a function\")\nshow_tasks()",
  "expected_stdout": "- [ ] Learn Python\n- [x] Drink coffee\n- [ ] Write a function",
  "hint": "The list method that adds an item to the end of a list (you used it back in lesson 14)."
},
};
