// AUTO-GENERATED by scripts/generate_quant.py
// Runner config for the Quant Programmer track lessons.

import type { ChallengeRunnerConfig } from "@/lib/featured-files";

export const QUANT_CONFIG: Record<string, ChallengeRunnerConfig> = {
  "quant-01-why-numpy": {
  "mode": "predict",
  "code": "import numpy as np, time\nn = 1_000_000\nxs = list(range(n))\narr = np.arange(n)\nprint(sum(xs) == int(arr.sum()))",
  "expected_stdout": "True",
  "prompt": "True or False?"
},
  "quant-02-creating-arrays": {
  "mode": "fillblank",
  "template": "import numpy as np\na = np.array([1.0, 2.0, 3.0])\nb = np.___(3)\nc = np.___(0, 1, 5)\nprint(a, b, c, sep=' | ')",
  "expected_stdout": "[1. 2. 3.] | [0. 0. 0.] | [0.   0.25 0.5  0.75 1.  ]",
  "hint": "One blank is `zeros`, the other is `linspace`."
},
  "quant-03-broadcasting": {
  "mode": "predict",
  "code": "import numpy as np\nM = np.zeros((4, 3))\nrow = np.array([10, 20, 30])\nprint((M + row)[0])",
  "expected_stdout": "[10. 20. 30.]",
  "prompt": "Type the row exactly as numpy prints it."
},
  "quant-04-boolean-masks": {
  "mode": "fillblank",
  "template": "import numpy as np\nr = np.array([-0.02, 0.01, -0.005, 0.015, 0.0, 0.03])\npositive = r[r ___ 0]\nprint(positive)",
  "expected_stdout": "[0.01  0.015 0.03 ]",
  "hint": "Strictly positive \u2014 zero doesn't count."
},
  "quant-05-covariance-via-matrix-algebra": {
  "mode": "fillblank",
  "template": "import numpy as np\nrng = np.random.default_rng(0)\nX = rng.normal(size=(1000, 2))\nXd = X - X.mean(axis=0)\ncov = Xd.___ @ Xd / X.shape[0]\nprint(np.round(cov, 2))",
  "expected_stdout": "[[ 1.04 -0.02]\n [-0.02  0.96]]",
  "hint": "Two-letter attribute on every numpy array."
},
  "quant-06-reproducible-random-numbers": {
  "mode": "fillblank",
  "template": "import numpy as np\na = np.random.default_rng(___).normal(size=3)\nb = np.random.default_rng(42).normal(size=3)\nprint(np.array_equal(a, b))",
  "expected_stdout": "True",
  "hint": "Use 42."
},
  "quant-07-statistical-reductions": {
  "mode": "fillblank",
  "template": "import numpy as np\nrng = np.random.default_rng(0)\nr = rng.normal(loc=0.001, scale=0.02, size=10_000)\nprint(round(r.___(), 4), round(r.___(), 4), round(np.___(r, 95), 4))",
  "expected_stdout": "0.0011 0.02 0.0338",
  "hint": "Two methods, one function. All three are short, common names."
},
  "quant-08-why-numpy-is-fast": {
  "mode": "predict",
  "code": "import numpy as np\nx = np.arange(1_000_000)\nprint(int(x.sum()))",
  "expected_stdout": "499999500000",
  "prompt": "Type the integer."
},
  "quant-09-vectorising-a-rolling-mean": {
  "mode": "fillblank",
  "template": "import numpy as np\nx = np.array([1, 2, 3, 4, 5, 6], dtype=float)\nw = 3\nc = np.concatenate(([0], np.___(x)))\nroll = (c[w:] - c[:-w]) / w\nprint(roll)",
  "expected_stdout": "[2. 3. 4. 5.]",
  "hint": "It's literally called the cumulative sum."
},
  "quant-10-plot-a-price-path": {
  "mode": "matplot",
  "template": "import numpy as np, matplotlib.pyplot as plt\nrng = np.random.default_rng(0)\nshocks = rng.normal(0, 0.01, 252)\nprice = 100 * np.exp(np.cumsum(shocks))\nplt.plot(___)\nplt.title('Simulated price path'); plt.xlabel('day'); plt.ylabel('price')\nprint('plotted')",
  "expected_stdout": "plotted",
  "hint": "It's a single variable name."
},
  "quant-11-dataframes-from-csv": {
  "mode": "fillblank",
  "template": "import pandas as pd\ndf = pd.___('/data/quant/spy.csv')\nprint(df.shape)",
  "expected_stdout": "(2766, 7)",
  "hint": "Three letters, then _csv.",
  "datasets": [
    "spy"
  ]
},
  "quant-12-loc-versus-iloc": {
  "mode": "predict",
  "code": "import pandas as pd\ndf = pd.DataFrame({'price': [100, 101, 99]}, index=['a', 'b', 'c'])\nprint(df.iloc[0]['price'], df.loc['b', 'price'])",
  "expected_stdout": "100 101",
  "prompt": "Two space-separated numbers."
},
  "quant-13-boolean-filtering-on-real-prices": {
  "mode": "fillblank",
  "template": "import pandas as pd\ndf = pd.read_csv('/data/quant/spy.csv')\nup = (df['close'] ___ df['open']).sum()\nprint(up)",
  "expected_stdout": "1487",
  "hint": "Same comparison operator you'd use on plain numbers.",
  "datasets": [
    "spy"
  ]
},
  "quant-14-daily-and-log-returns": {
  "mode": "matplot",
  "template": "import pandas as pd, numpy as np, matplotlib.pyplot as plt\ndf = pd.read_csv('/data/quant/spy.csv')\nsimple = df['adj_close'].___().dropna()\nlog_r = np.log(df['adj_close'] / df['adj_close'].shift(1)).dropna()\nplt.hist(log_r, bins=60)\nplt.title('SPY log returns'); plt.xlabel('return'); plt.ylabel('count')\nprint(round(simple.std(), 4), round(log_r.std(), 4))",
  "expected_stdout": "0.0112 0.0112",
  "hint": "It's the method that gives one-period percentage change.",
  "datasets": [
    "spy"
  ]
},
  "quant-15-rolling-volatility": {
  "mode": "matplot",
  "template": "import pandas as pd, numpy as np, matplotlib.pyplot as plt\ndf = pd.read_csv('/data/quant/spy.csv')\nr = df['adj_close'].pct_change()\nvol = r.rolling(30).___() * np.sqrt(252)\nplt.plot(vol)\nplt.title('SPY 30-day rolling vol'); plt.xlabel('day'); plt.ylabel('annualised vol')\nprint(round(vol.max(), 3))",
  "expected_stdout": "0.821",
  "hint": "Three letters.",
  "datasets": [
    "spy"
  ]
},
  "quant-16-groupby-year": {
  "mode": "fillblank",
  "template": "import pandas as pd\ndf = pd.read_csv('/data/quant/spy.csv')\ndf['year'] = pd.to_datetime(df['date']).dt.year\nby_year = df.___('year')['adj_close'].apply(lambda s: s.pct_change().mean())\nprint(round(by_year[2020], 5))",
  "expected_stdout": "0.00085",
  "hint": "Seven letters.",
  "datasets": [
    "spy"
  ]
},
  "quant-17-aligning-two-series": {
  "mode": "fillblank",
  "template": "import pandas as pd\nspy = pd.read_csv('/data/quant/spy.csv')\naapl = pd.read_csv('/data/quant/aapl.csv')\njoined = pd.merge(spy, aapl, on='date', how='___', suffixes=('_spy', '_aapl'))\nprint(joined.shape)",
  "expected_stdout": "(2766, 13)",
  "hint": "Same name as the SQL join.",
  "datasets": [
    "spy",
    "aapl"
  ]
},
  "quant-18-fitting-a-normal-to-returns": {
  "mode": "matplot",
  "template": "import pandas as pd, numpy as np, matplotlib.pyplot as plt\nfrom scipy.stats import norm\ndf = pd.read_csv('/data/quant/spy.csv')\nr = df['adj_close'].pct_change().dropna()\nmu, sigma = norm.___(r)\nxs = np.linspace(r.min(), r.max(), 200)\nplt.hist(r, bins=80, density=True, alpha=0.6)\nplt.plot(xs, norm.pdf(xs, mu, sigma))\nplt.title('SPY daily returns vs normal fit')\nprint(round(sigma, 4))",
  "expected_stdout": "0.0112",
  "hint": "Three letters.",
  "datasets": [
    "spy"
  ]
},
  "quant-19-ols-beta-of-aapl-on-spy": {
  "mode": "fillblank",
  "template": "import pandas as pd, statsmodels.api as sm\nspy = pd.read_csv('/data/quant/spy.csv')['adj_close'].pct_change()\naapl = pd.read_csv('/data/quant/aapl.csv')['adj_close'].pct_change()\ndf = pd.concat([spy, aapl], axis=1).dropna()\nX = sm.add_constant(df.iloc[:, 0])\nres = sm.___(df.iloc[:, 1], X).fit()\nprint(round(res.params.iloc[1], 2))",
  "expected_stdout": "1.21",
  "hint": "Three letters in caps.",
  "datasets": [
    "spy",
    "aapl"
  ]
},
  "quant-20-stationarity-preview": {
  "mode": "predict",
  "code": "import pandas as pd\nfrom statsmodels.tsa.stattools import adfuller\ndf = pd.read_csv('/data/quant/spy.csv')\np_price = adfuller(df['adj_close'])[1]\np_ret = adfuller(df['adj_close'].pct_change().dropna())[1]\nprint(p_price > 0.05, p_ret < 0.05)",
  "expected_stdout": "True True",
  "prompt": "Two booleans."
},
};
