// AUTO-GENERATED by scripts/generate_quant.py
// Runner config for the Quant Programmer track lessons.

import type { ChallengeRunnerConfig } from "@/lib/featured-files";

export const QUANT_CONFIG: Record<string, ChallengeRunnerConfig> = {
  // (no lessons defined yet)
};
